### ISSUE TITLE
Fiona fails on import when installed in an Anaconda fresh environment

### ISSUE THREAD

**Issue by datapythonista** [Toblerity/Fiona#1042]
## Expected behavior and actual behavior.

Fiona fails when imported in a clean conda environment

## Steps to reproduce the problem.

```bash
$ conda create -n fiona
$ conda activate fiona
$ conda install -c conda-forge fiona
Downloading and Extracting Packages
python-3.9.7         | 27.5 MB   | ################################################################################################################################## | 100% 
gdal-3.3.2           | 1.7 MB    | ################################################################################################################################## | 100% 
fiona-1.8.20         | 1.1 MB    | ################################################################################################################################## | 100% 
shapely-1.7.1        | 442 KB    | ################################################################################################################################## | 100% 
setuptools-58.0.4    | 960 KB    | ################################################################################################################################## | 100%
```

```python
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mgarcia/miniconda3/envs/fiona/lib/python3.9/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/mgarcia/miniconda3/envs/fiona/lib/python3.9/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
```

## Operating system

Linux Fedora
```bash
$ uname -a
Linux xps 5.11.22-100.fc32.x86_64 #1 SMP Wed May 19 18:58:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## Fiona and GDAL version and provenance

Install with Anaconda from conda-forge:
```
fiona-1.8.20
gdal-3.3.2
```

**Comment by sgillies** [comment]
@datapythonista I'm sorry you can't import fiona, but this project is only concerned about the fiona source code and the wheels on the Python package index. Please check the fiona or gdal feedstock repos in the conda-forge org to see if it's a known problem yet.

**Comment by datapythonista** [comment]
Thanks, looks like it's been already reported there: https://github.com/conda-forge/fiona-feedstock/issues/138

And a workaround in RedHat based distros is to install `dnf install libnsl`.
