### ISSUE TITLE
Error when trying to download zipped shapefile from URL

### ISSUE THREAD

**Issue by jtamerius** [Toblerity/Fiona#1050]
Hey All,

I am trying to download the following zipped shapefile: https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40shpf2021shp.zip

I have manually downloaded and tested the file and everything seems fine.  But, when I use geopandas to download the file I am getting an error in Fiona.
```
gdf = gpd.read_file('https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40shpf2021shp.zip')

Traceback (most recent call last):
  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: '/vsimem/a3c8a8d548f540629ee5da2e83015e2f' not recognized as a supported file format.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\james.tamerius\AppData\Local\Continuum\anaconda3\envs\caret_evi\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\james.tamerius\AppData\Local\Continuum\anaconda3\envs\caret_evi\lib\site-packages\geopandas\io\file.py", line 160, in _read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "C:\Users\james.tamerius\AppData\Local\Continuum\anaconda3\envs\caret_evi\lib\site-packages\fiona\collection.py", line 555, in __init__
    super(BytesCollection, self).__init__(self.virtual_file, vsi=filetype,
  File "C:\Users\james.tamerius\AppData\Local\Continuum\anaconda3\envs\caret_evi\lib\site-packages\fiona\collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 540, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: '/vsimem/a3c8a8d548f540629ee5da2e83015e2f' not recognized as a supported file format.
```

I am operating on Windows 10
I am using fiona 1.8.20  and gdal 3.3.1 from conda-forge.

Thanks for any help in advance!

**Comment by jtamerius** [comment]
This resolved itself overnight! Must have been a server side bug.
