### ISSUE TITLE
Zipped shapefile reading error

### ISSUE THREAD

**Issue by jsta** [Toblerity/Fiona#1086]
## Expected behavior and actual behavior.

Trying to read from a zipped shapefile.

## Steps to reproduce the problem.

`python -c "import os; print(os.path.exists('10197478640.zip'))" `
> True

`python -c "import geopandas; geopandas.read_file('10197478640.zip')"`
> Traceback (most recent call last):
  File "fiona\_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona\_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: '/vsizip/10197478640.zip' does not exist in the file system, and is not recognized as a supported dataset name.

## Operating system

Windows 10

## Fiona and GDAL version and provenance

GDAL 3.4.2 installed from conda-forge
1.8.21 installed from conda-forge

**Comment by jsta** [comment]
Issue was that the zip file was empty even though it did exist.
