### ISSUE TITLE
path.sep goes missing when importing in a debugger in Python 3.10

### ISSUE THREAD

**Issue by idanmiara** [Toblerity/Fiona#1143]
Hi,

I think I'm encountering the same error as https://github.com/pyproj4/pyproj/issues/1028 but with Fiona instead of pyproj

Also related:
https://github.com/pytest-dev/pytest/issues/9791#issuecomment-1081617058

## Expected behavior and actual behavior.

The following code should run without any error:
```
import os
print(os.path.sep)
import fiona
print(os.path.sep)
```

But, I get the following exception:

```
/Users/idan.miara/.pyenv/versions/py310/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 49298 --file /Users/idan.miara/workspace/temp/temp.py 
/
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/idan.miara/workspace/temp/temp.py", line 4, in <module>
    print(os.path.sep)
AttributeError: module 'posixpath' has no attribute 'sep'```

## Steps to reproduce the problem.
Run the code snippet above in Python 3.10 in debug mode (I use PyCharm)

The problem is reproducible on:
Python 3.10.7 in debug mode

The problem is not reproducible on:
Python 3.10.7 in non-debug mode (normal run)
Python 3.9.12 in either mode

## Operating system

For example: Mac OS X 12.6

## Fiona and GDAL version and provenance

Fiona 1.8.21 installed from PyPI using pip version 22.2.2.

**Comment by sgillies** [comment]
@idanmiara thanks for the report! I expect this could affect rasterio in some ways, too.

Fiona 1.9.x no longer pins cython in pyproject.toml, so the sdist is fine. The wheels were probably built with a buggy version of cython. Fiona 1.8.x wheels and sdists will be affected.

**Comment by idanmiara** [comment]
Hi @sgillies
Thanks for looking into this! 

I'm understanding that Fiona 1.9 is atill Alpha, and this bug won't be fixed for 1.8 because it pins the buggy Cython version?
If so - didn't Cython release a stable bugfix release that can be applied to Fiona 1.8?

This bug means that we can't use pytest with stable Fiona on Python 3.10.

**Comment by sgillies** [comment]
@idanmiara I think a 1.8.22 release is appropriate. It's only the use of Python's development mode that is prevented, no? Or is a future version of pytest switching to requiring development mode?

**Comment by idanmiara** [comment]
I'm not familiar with Python's development mode, but when I run any pytest
test in PyCharm, that imports fiona, it fails with that error.

I did find a workaround, adding the following code at the top of the test
will make the test pass:
```
import os.path
sep = os.path.sep
import fiona
os.path.sep = sep
```

**Comment by sgillies** [comment]
Done!
