### ISSUE TITLE
Overflow error on large int

### ISSUE THREAD

**Issue by perrygeo** [Toblerity/Fiona#117]
Quickest way to recreate:

```
from geopandas import GeoDataFrame 
from shapely.geometry import Point

df = GeoDataFrame([{'geometry' : Point(0,0), 'value1': 109691494175 }])
df.to_file("test.json", driver="GeoJSON")
```
gives me

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    df.to_file("test.json", driver="GeoJSON")
  File "/home/mperry/src/geopandas/geopandas/geodataframe.py", line 305, in to_file
    c.write(feature(i, row))
  File "/home/mperry/env/geopandas/lib/python2.7/site-packages/fiona/collection.py", line 220, in write
    self.writerecords([record])
  File "/home/mperry/env/geopandas/lib/python2.7/site-packages/fiona/collection.py", line 214, in writerecords
    self.session.writerecs(records, self)
  File "ogrext.pyx", line 1018, in fiona.ogrext.WritingSession.writerecs (src/fiona/ogrext.c:17002)
  File "ogrext.pyx", line 509, in fiona.ogrext.OGRFeatureBuilder.build (src/fiona/ogrext.c:9521)
OverflowError: value too large to convert to int
```

Using Fiona==1.1.5

**Comment by sgillies** [comment]
Update on state of ints for OGR: http://lists.osgeo.org/pipermail/gdal-dev/2015-January/040849.html. 64-bit to land in GDAL 2.0.
