### ISSUE TITLE
New CRS class incompatible with rasterio

### ISSUE THREAD

**Issue by loicdtx** [Toblerity/Fiona#1247]
The new `CRS` class looks great, however, when I run:

```python
from rasterio.crs import CRS
import fiona
con = fiona.open('/tmp/crs_test.geojson', 'w', crs=CRS.from_epsg(4326), schema={'geometry': 'Point'}, driver='GeoJSON')
```

I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/loic/.virtualenvs/tmp-a470ab4fd8bf3b9/lib/python3.10/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
  File "/home/loic/.virtualenvs/tmp-a470ab4fd8bf3b9/lib/python3.10/site-packages/fiona/__init__.py", line 347, in open
    colxn = Collection(
  File "/home/loic/.virtualenvs/tmp-a470ab4fd8bf3b9/lib/python3.10/site-packages/fiona/collection.py", line 98, in __init__
    raise TypeError("invalid crs: %r" % crs)
TypeError: invalid crs: CRS.from_epsg(4326)
```

I assume (perhaps wrongly) that the `CRS` from various libraries are meant to be compatible with each others.

Also I vaguely remember being able to pass a crs object coming from rasterio before the introduction of the fiona `CRS` class, but I was unable to reproduce that just now using `fiona==1.8.22`

```python
>>> fiona.show_versions()
Fiona version: 1.9.2
GDAL version: 3.5.3
PROJ version: 9.0.1

OS: Linux 5.19.0-38-generic
Python: 3.10.6
Python executable: '/home/loic/.virtualenvs/tmp-a470ab4fd8bf3b9/bin/python'


# Rasterio
>>> rasterio.show_versions()
rasterio info:
  rasterio: 1.3.6
      GDAL: 3.5.3
      PROJ: 9.0.1
      GEOS: 3.11.1
 PROJ DATA: /home/loic/.virtualenvs/tmp-a470ab4fd8bf3b9/lib/python3.10/site-packages/rasterio/proj_data
 GDAL DATA: /home/loic/.virtualenvs/tmp-a470ab4fd8bf3b9/lib/python3.10/site-packages/rasterio/gdal_data

System:
    python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
executable: /home/loic/.virtualenvs/tmp-a470ab4fd8bf3b9/bin/python
   machine: Linux-5.19.0-38-generic-x86_64-with-glibc2.35

Python deps:
    affine: 2.4.0
     attrs: 22.2.0
   certifi: 2022.12.07
     click: 8.1.3
     cligj: 0.7.2
    cython: None
     numpy: 1.24.2
    snuggs: 1.4.7
click-plugins: None
setuptools: 59.6.0
```

**Comment by sgillies** [comment]
@loicdtx yes, we should accept Rasterio CRS objects and I'll make it so for 1.9.3, which is planned to be released today.

**Comment by loicdtx** [comment]
Fantastic, thanks @sgillies for the quick fix!!
I confirm the above snippet works as expected using fiona 1.9.3
