### ISSUE TITLE
Can't load file with `include_fields` parameter set

### ISSUE THREAD

**Issue by datengraben** [Toblerity/Fiona#1279]
Thanks for open sourcing fiona and your work!

## Expected behavior and actual behavior.

I expected to read any GeoJSON with `include_fields` set, on `fiona.open` in a Fiona version > 1.9+
But I get `fiona.errors.DriverError: Driver does not support ignore_fields`.

Because this is stated in GeoPandas-Docs: https://geopandas.org/en/v0.13.2/docs/user_guide/io.html#field-column-filters

But I validated it with direct invocation of fiona too (see the examples below).

## Steps to reproduce the problem.

On python 3.9
Install latest Version of fiona: `1.9.4-post`

```python
import pandas as pd
import geopandas as gpd
import fiona

print("Pandas", pd.__version__)
print("GeoPandas", gpd.__version__)
print("Fiona", fiona.__version__)

fiona.supported_drivers["NAS"] = "raw"
print(fiona.supported_drivers)

# Only pass through geometry
fields=['id', 'geometry']

# Fails with pandas
# df = gpd.read_file('./example.geojson', include_fields=fields)

# Also fails directly with fiona
fiona.open('./example.geojson', include_fields=fields)
```

And the following GeoJSON as `example.geojson`

```json
{
  "type": "FeatureCollection",
  "generator": "overpass-ide",
  "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.",
  "timestamp": "2023-06-28T15:39:46Z",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "@id": "relation/1633812",
        "addr:city": "Freiburg im Breisgau",
        "addr:housenumber": "8",
        "addr:postcode": "79115",
        "addr:street": "Lörracher Straße",
        "check_date:opening_hours": "2022-07-22",
        "name": "Edeka",
        "opening_hours": "Mo-Sa 08:00-22:00",
        "operator": "Edeka",
        "organic": "yes",
        "shop": "supermarket",
        "type": "multipolygon",
        "website": "http://mein.edeka.de/eh/de/suedwest/2349/index.jsp",
        "wheelchair": "yes",
        "@geometry": "center"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          7.8247395,
          47.9815198
        ]
      },
      "id": "relation/1633812"
    }
]
}
```

I'll get the following result:
```
Pandas 2.0.2
GeoPandas 0.13.2
Fiona 1.9.4.post1
{'DXF': 'rw', 'CSV': 'raw', 'OpenFileGDB': 'raw', 'ESRIJSON': 'r', 'ESRI Shapefile': 'raw', 'FlatGeobuf': 'raw', 'GeoJSON': 'raw', 'GeoJSONSeq': 'raw', 'GPKG': 'raw', 'GML': 'rw', 'OGR_GMT': 'rw', 'GPX': 'rw', 'MapInfo File': 'raw', 'DGN': 'raw', 'S57': 'r', 'SQLite': 'raw', 'TopoJSON': 'r', 'NAS': 'raw'}
Traceback (most recent call last):
  File "/home/chris/Code/transform-example.py", line 16, in <module>
    fiona.open('./example.geojson', include_fields=fields)
  File "/home/chris/Code/.venv/lib/python3.9/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
  File "/home/chris/Code/.venv/lib/python3.9/site-packages/fiona/__init__.py", line 292, in open
    colxn = Collection(
  File "/home/chris/Code/.venv/lib/python3.9/site-packages/fiona/collection.py", line 243, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 607, in fiona.ogrext.Session.start
fiona.errors.DriverError: Driver does not support ignore_fields

```

## Operating system

Ubuntu 22.04.2 LTS

## Fiona and GDAL version and provenance

`1.9.4.post1` from PyPI using pip version 23.1.2

GDAL 3.4.1, released 2021/12/27 installed via apt-get

**Comment by sgillies** [comment]
@datengraben there are only a few OGR formats that support [GDAL RFC 29 Desired Fields](https://gdal.org/development/rfc/rfc29_desired_fields.html) and [GeoJSON is not one of them](https://github.com/OSGeo/gdal/blob/6e9103bd5acb1ff8da305c4e77fa30335ffa3b70/ogr/ogrsf_frmts/geojson/ogrgeojsonwritelayer.cpp#L322).

Unfortunately, there's no static metadata about this capability across all drivers, so we can't provide a list of formats that provide it. Programs that pass this option to `fiona.open()` must be prepared to catch a DriverError and reopen without using the option.
