### ISSUE TITLE
error running cli documentation example

### ISSUE THREAD

**Issue by aborruso** [Toblerity/Fiona#1450]
## Expected behavior and actual behavior.

I expect to launch the documentation examples without having errors.

## Steps to reproduce the problem.

I run the [Counting vertices in a feature collection](https://fiona.readthedocs.io/en/stable/cli.html#sizing-up-and-simplifying-shapes) first sample command

```
fio cat zip+https://github.com/Toblerity/Fiona/files/14749922/rmnp.zip
```

And I have the below error

<details>
  <summary>my error</summary>

```
Traceback (most recent call last):
  File "/home/aborruso/.local/bin/fio", line 8, in <module>
    sys.exit(main_group())
             ^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/fiona/fio/__init__.py", line 18, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/fiona/fio/cat.py", line 111, in cat
    with fiona.open(path, layer=lyr, **open_options) as src:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/fiona/__init__.py", line 342, in open
    colxn = Collection(
            ^^^^^^^^^^^
  File "/home/aborruso/.local/lib/python3.11/site-packages/fiona/collection.py", line 226, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 887, in fiona.ogrext.Session.start
ValueError: Null layer: <closed Collection '/vsizip/vsicurl/https://github.com/Toblerity/Fiona/files/14749922/rmnp.zip:rmnp', mode 'r' at 0x7f0ed9268790> rmnp
```
</details>

## Operating system

Debian 12

## Fiona and GDAL version and provenance

I have fio, version 1.10.1 installed via pip

I have GDAL 3.8.3, released 2024/01/04 compiled via code.

**Comment by aborruso** [comment]
I don't know if it is useful: I have no errors running this

```
fio cat zip+https://github.com/Toblerity/Fiona/files/11151652/coutwildrnp.zip
```

**Comment by sgillies** [comment]
@aborruso I'm unable to reproduce the problem with rmnp.zip using a 1.10.1 wheel from PyPI that includes GDAL 3.9.2. I'm not aware of any issues specific to GDAL 3.8.3, but I've also never used included it in PyPI wheels, only version 3.8.4.
