### ISSUE TITLE
Driver specific strange behavior when creating/writing a file to cloud bucket using opener argument

### ISSUE THREAD

**Issue by digital-idiot** [Toblerity/Fiona#1476]
## Expected behavior and actual behavior.

Creation and write executed successfully or fail in the same way

## Steps to reproduce the problem.

Below is the script to reproduce the problem. First the common part of the script followed by variations and subsequent outcomes.

<details>
<summary>Common Code Section</summary>

```python
import fiona
import fsspec
from fiona.crs import from_epsg


fs = fsspec.filesystem(protocol="s3", key="KKKKKKKKKK", secret="XXXXXXXXXXXXX")

schema = {
    'geometry': 'Polygon',
    'properties': {
        'id': 'int',
        'name': 'str'
    }
}

# Create some sample polygons
polygons = [
    {
        'geometry': {
            'type': 'Polygon',
            'coordinates': [[(0, 0), (0, 1), (1, 1), (1, 0), (0, 0)]]
        },
        'properties': {
            'id': 1,
            'name': 'square'
        }
    },
    {
        'geometry': {
            'type': 'Polygon',
            'coordinates': [[(2, 2), (2, 3), (3, 2), (2, 2)]]
        },
        'properties': {
            'id': 2,
            'name': 'triangle'
        }
    }
]
```

</details>

<details>
<summary>Export to GeoJSON</summary>

```python
with fiona.open(
    's3://bucket/path/vector_layer.geojson',
    'w',
    driver='GeoJSON',
    crs=from_epsg(4326),
    schema=schema,
    opener=fs
) as dst:
    for polygon in polygons:
        dst.write(polygon)

print("Write Completed Successfully!")
```
#### Output

```python
Write Completed Successfully!
```
</details>

<details>
<summary>Export to GPKG</summary>

```python
with fiona.open(
    's3://bucket/path/vector_layer.gpkg',
    'w',
    driver='GPKG',
    crs=from_epsg(4326),
    schema=schema,
    opener=fs
) as dst:
    for polygon in polygons:
        dst.write(polygon)

print("Write Completed Successfully!")
```
#### Output

```python
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
File fiona/ogrext.pyx:175, in fiona.ogrext.gdal_create()

File fiona/_err.pyx:291, in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: sqlite3_open(/vsis3/bucket/path/vector_layer.gpkg) failed: unable to open database file

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
Cell In[45], line 1
----> 1 with fiona.open(
      2     's3://bucket/path/vector_layer.gpkg',
      3     'w',
      4     driver='GPKG',
      5     crs=from_epsg(4326),
      6     schema=schema,
      7     opener=fs
      8 ) as dst:
      9     for polygon in polygons:
     10         dst.write(polygon)

File ~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/env.py:457, in ensure_env_with_credentials.<locals>.wrapper(*args, **kwds)
    454     session = DummySession()
    456 with env_ctor(session=session):
--> 457     return f(*args, **kwds)

File ~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/__init__.py:303, in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, allow_unsupported_drivers, **kwargs)
    292     colxn = Collection(
    293         path,
    294         mode,
   (...)
    300         **kwargs
    301     )
    302 elif mode == "w":
--> 303     colxn = Collection(
    304         path,
    305         mode,
    306         crs=crs,
    307         driver=driver,
    308         schema=schema,
    309         encoding=encoding,
    310         layer=layer,
    311         enabled_drivers=enabled_drivers,
    312         crs_wkt=crs_wkt,
    313         allow_unsupported_drivers=allow_unsupported_drivers,
    314         **kwargs
    315     )
    316 else:
    317     raise ValueError("mode string must be one of {'r', 'w', 'a'}")

File ~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/collection.py:246, in Collection.__init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)
    244     elif self.mode in ("a", "w"):
    245         self.session = WritingSession()
--> 246         self.session.start(self, **kwargs)
    247 except OSError:
    248     self.session = None

File fiona/ogrext.pyx:1110, in fiona.ogrext.WritingSession.start()

File fiona/ogrext.pyx:1111, in fiona.ogrext.WritingSession.start()

File fiona/ogrext.pyx:179, in fiona.ogrext.gdal_create()

DriverError: sqlite3_open(/vsis3/bucket/path/vector_layer.gpkg) failed: unable to open database file
```
</details>

<details>
<summary>Export to ESRI Shapefile</summary>

```python
with fiona.open(
    's3://bucket/path/vector_layer.shp',
    'w',
    driver='ESRI Shapefile',
    crs=from_epsg(4326),
    schema=schema,
    opener=fs
) as dst:
    for polygon in polygons:
        dst.write(polygon)

print("Write Completed Successfully!")
```
#### Output

```python
---------------------------------------------------------------------------
CPLE_AppDefinedError                      Traceback (most recent call last)
File fiona/ogrext.pyx:1239, in fiona.ogrext.WritingSession.start()

File fiona/ogrext.pyx:1240, in fiona.ogrext.WritingSession.start()

File fiona/_err.pyx:291, in fiona._err.exc_wrap_pointer()

CPLE_AppDefinedError: Failed to create file /vsis3/bucket/path/vector_layer.shp: Permission denied

During handling of the above exception, another exception occurred:

DriverIOError                             Traceback (most recent call last)
Cell In[46], line 1
----> 1 with fiona.open(
      2     's3://bucket/path/vector_layer.shp',
      3     'w',
      4     driver='ESRI Shapefile',
      5     crs=from_epsg(4326),
      6     schema=schema,
      7     opener=fs
      8 ) as dst:
      9     for polygon in polygons:
     10         dst.write(polygon)

File ~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/env.py:457, in ensure_env_with_credentials.<locals>.wrapper(*args, **kwds)
    454     session = DummySession()
    456 with env_ctor(session=session):
--> 457     return f(*args, **kwds)

File ~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/__init__.py:303, in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, allow_unsupported_drivers, **kwargs)
    292     colxn = Collection(
    293         path,
    294         mode,
   (...)
    300         **kwargs
    301     )
    302 elif mode == "w":
--> 303     colxn = Collection(
    304         path,
    305         mode,
    306         crs=crs,
    307         driver=driver,
    308         schema=schema,
    309         encoding=encoding,
    310         layer=layer,
    311         enabled_drivers=enabled_drivers,
    312         crs_wkt=crs_wkt,
    313         allow_unsupported_drivers=allow_unsupported_drivers,
    314         **kwargs
    315     )
    316 else:
    317     raise ValueError("mode string must be one of {'r', 'w', 'a'}")

File ~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/collection.py:246, in Collection.__init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)
    244     elif self.mode in ("a", "w"):
    245         self.session = WritingSession()
--> 246         self.session.start(self, **kwargs)
    247 except OSError:
    248     self.session = None

File fiona/ogrext.pyx:1248, in fiona.ogrext.WritingSession.start()

DriverIOError: Failed to create file /vsis3/bucket/path/vector_layer.shp: Permission denied
```
</details>

Demonstrably, the creation of both `GPKG` and `ESRI Shapefile` fails but stating different errors. Since the creation and writing of `GeoJSON` is successful the underlying issue is unlikely to be an access issue or permission issue. So the question is are these expected behaviors? Is the requirement of creating auxiliary files (.dbf, .prj etc) in the case of  `ESRI Shapefile` playing a role?

## Operating system

MacOS 15.2 (24C101) [Kernel: Darwin 24.2.0]

## Fiona and GDAL version and provenance
* Environment Manager: `micromamba`
* Channel: `conda-forge`
  - `fiona=1.9.6`
  - `GDAL=3.9.2`

**Comment by sgillies** [comment]
@digital-idiot the `opener` keyword argument was added in Fiona version 1.10.0. It doesn't exist in 1.9.6. Therefore, this is what is happening: fiona gives "s3://bucket/path/vector_layer.shp" to GDAL's native I/O, not to fsspec, and since GDAL doesn't have any credentials, the connection fails.

I'm going to close this issue as the behavior you see is expected with Fiona 1.9.6. If you update to 1.10.1, I think you'll get the results that you're looking for.

**Comment by digital-idiot** [comment]
I updated `fiona` to `1.10.1` but the problem remains. However, now it seems like a `fsspec` / `s3fs` issue:

```python
Exception ignored in: <function AbstractBufferedFile.__del__ at 0x10788b560>
Traceback (most recent call last):
  File "~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fsspec/spec.py", line 2216, in __del__
    self.close()
  File "~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fsspec/spec.py", line 2177, in close
    if not self.forced:
           ^^^^^^^^^^^
AttributeError: 'S3File' object has no attribute 'forced'
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
File fiona/ogrext.pyx:166, in fiona.ogrext.gdal_create()

File fiona/_err.pyx:317, in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: sqlite3_open(/vsifiopener_cd7d09704bbd4126afe297bc0bf8bef9/s3://bucket/path/vector_layer.gpkg) failed: unable to open database file

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
     17 polygons = [
     18     {
     19         'geometry': {
   (...)
     37     }
     38 ]
     40 errors = list()
---> 42 with fiona.open(
     43         's3://bucket/path/vector_layer.gpkg',
     44         'w',
     45         driver='GPKG',
     46         crs=from_epsg(4326),
     47         schema=schema,
     48         opener=fs
     49     ) as dst:
     50         for polygon in polygons:
     51             dst.write(polygon)

File ~/micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/env.py:457, in ensure_env_with_credentials.<locals>.wrapper(*args, **kwds)
    454     session = DummySession()
    456 with env_ctor(session=session):
--> 457     return f(*args, **kwds)

File ~/micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/__init__.py:357, in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, opener, **kwargs)
    342     colxn = Collection(
    343         path,
    344         mode,
   (...)
    354         **kwargs
    355     )
    356 elif mode == "w":
--> 357     colxn = Collection(
    358         path,
    359         mode,
    360         crs=crs,
    361         driver=driver,
    362         schema=schema,
    363         encoding=encoding,
    364         layer=layer,
    365         ignore_fields=ignore_fields,
    366         include_fields=include_fields,
    367         ignore_geometry=ignore_geometry,
    368         wkt_version=wkt_version,
    369         enabled_drivers=enabled_drivers,
    370         crs_wkt=crs_wkt,
    371         allow_unsupported_drivers=allow_unsupported_drivers,
    372         **kwargs
    373     )
    374 else:
    375     raise ValueError("mode string must be one of {'r', 'w', 'a'}")

File ~/micromamba/envs/PyDev/lib/python3.12/site-packages/fiona/collection.py:229, in Collection.__init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)
    227     elif self.mode in ("a", "w"):
    228         self.session = WritingSession()
--> 229         self.session.start(self, **kwargs)
    230 except OSError:
    231     self.session = None

File fiona/ogrext.pyx:1370, in fiona.ogrext.WritingSession.start()

File fiona/ogrext.pyx:1371, in fiona.ogrext.WritingSession.start()

File fiona/ogrext.pyx:170, in fiona.ogrext.gdal_create()

DriverError: sqlite3_open(/vsifiopener_cd7d09704bbd4126afe297bc0bf8bef9/s3://bucket/path/vector_layer.gpkg) failed: unable to open database file
```
