### ISSUE TITLE
pip install Issue

### ISSUE THREAD

**Issue by nyotta** [Toblerity/Fiona#220]
Not sure if this is a config issue on my end, but would love some input as to why the install is failing.

I tried using `pip install fiona`, `pip install` with the .whl file, and `easy_install fiona`:

```
C:\Users\bnnyotta\Downloads>pip install fiona
Collecting fiona
  Using cached Fiona-1.5.1.tar.gz
    WARNING:root:Failed to get options via gdal-config: [Error 2] The system can
not find the file specified
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'metadata_version'
      warnings.warn(msg)
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_python'
      warnings.warn(msg)
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_external'
      warnings.warn(msg)
Requirement already satisfied (use --upgrade to upgrade): cligj in c:\python27\l
ib\site-packages (from fiona)
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib
\site-packages (from fiona)
Requirement already satisfied (use --upgrade to upgrade): click>=3.0 in c:\pytho
n27\lib\site-packages (from cligj->fiona)
Installing collected packages: fiona
  Running setup.py install for fiona
    WARNING:root:Failed to get options via gdal-config: [Error 2] The system can
not find the file specified
    building 'fiona._transform' extension
    C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\B
in\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python
27\PC /Tpfiona/_transform.cpp /Fobuild\temp.win32-2.7\Release\fiona/_transform.o
bj
    _transform.cpp
    fiona/_transform.cpp(236) : fatal error C1083: Cannot open include file: 'gd
al.h': No such file or directory
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'metadata_version'
      warnings.warn(msg)
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_python'
      warnings.warn(msg)
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_external'
      warnings.warn(msg)
    error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++
 for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
    Complete output from command C:\Python27\python.exe -c "import setuptools, t
okenize;__file__='c:\\users\\bnnyotta\\appdata\\local\\temp\\pip-build-xxjvoi\\f
iona\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().re
place('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\bnnyotta\appd
ata\local\temp\pip-2p1lmd-record\install-record.txt --single-version-externally-
managed --compile:
    WARNING:root:Failed to get options via gdal-config: [Error 2] The system can
not find the file specified

    running install

    running build

    running build_py

    creating build

    creating build\lib.win32-2.7

    creating build\lib.win32-2.7\fiona

    copying .\fiona\collection.py -> build\lib.win32-2.7\fiona

    copying .\fiona\crs.py -> build\lib.win32-2.7\fiona

    copying .\fiona\errors.py -> build\lib.win32-2.7\fiona

    copying .\fiona\inspector.py -> build\lib.win32-2.7\fiona

    copying .\fiona\odict.py -> build\lib.win32-2.7\fiona

    copying .\fiona\rfc3339.py -> build\lib.win32-2.7\fiona

    copying .\fiona\tool.py -> build\lib.win32-2.7\fiona

    copying .\fiona\transform.py -> build\lib.win32-2.7\fiona

    copying .\fiona\__init__.py -> build\lib.win32-2.7\fiona

    creating build\lib.win32-2.7\fiona\fio

    copying .\fiona\fio\bounds.py -> build\lib.win32-2.7\fiona\fio

    copying .\fiona\fio\cat.py -> build\lib.win32-2.7\fiona\fio

    copying .\fiona\fio\cli.py -> build\lib.win32-2.7\fiona\fio

    copying .\fiona\fio\fio.py -> build\lib.win32-2.7\fiona\fio

    copying .\fiona\fio\__init__.py -> build\lib.win32-2.7\fiona\fio

    running build_ext

    building 'fiona._transform' extension

    creating build\temp.win32-2.7

    creating build\temp.win32-2.7\Release

    creating build\temp.win32-2.7\Release\fiona

    C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\B
in\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python
27\PC /Tpfiona/_transform.cpp /Fobuild\temp.win32-2.7\Release\fiona/_transform.o
bj

    _transform.cpp

    fiona/_transform.cpp(236) : fatal error C1083: Cannot open include file: 'gd
al.h': No such file or directory

    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'metadata_version'

      warnings.warn(msg)

    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_python'

      warnings.warn(msg)

    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_external'

      warnings.warn(msg)

    error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++
 for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
    Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:
\\users\\bnnyotta\\appdata\\local\\temp\\pip-build-xxjvoi\\fiona\\setup.py';exec
(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'),
 __file__, 'exec'))" install --record c:\users\bnnyotta\appdata\local\temp\pip-2
p1lmd-record\install-record.txt --single-version-externally-managed --compile" f
ailed with error code 1 in c:\users\bnnyotta\appdata\local\temp\pip-build-xxjvoi
\fiona
```

The .whl install is strange because I have wheel installed and I used it a few minute before to install another package Shapely,
```
C:\Users\bnnyotta\Downloads>pip install Fiona-1.5.1-cp27-none-macosx_10_6_intel.
macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

Fiona-1.5.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.mac
osx_10_10_intel.macosx_10_10_x86_64.whl is not a supported wheel on this platfor
m.
```
Easy_Install:
```
C:\Users\bnnyotta\Downloads>easy_install fiona
Searching for fiona
Reading https://pypi.python.org/simple/fiona/
Best match: Fiona 1.5.1
Downloading https://pypi.python.org/packages/source/F/Fiona/Fiona-1.5.1.tar.gz#m
d5=e976183d253c33c0c66d67753c52b1a7
Processing Fiona-1.5.1.tar.gz
Writing c:\users\bnnyotta\appdata\local\temp\easy_install-aractu\Fiona-1.5.1\set
up.cfg
Running Fiona-1.5.1\setup.py -q bdist_egg --dist-dir c:\users\bnnyotta\appdata\l
ocal\temp\easy_install-aractu\Fiona-1.5.1\egg-dist-tmp-foolm1
WARNING:root:Failed to get options via gdal-config: [Error 2] The system cannot
find the file specified
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'metadata_version'
  warnings.warn(msg)
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'requires_python'
  warnings.warn(msg)
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'requires_external'
  warnings.warn(msg)
_transform.cpp
fiona/_transform.cpp(236) : fatal error C1083: Cannot open include file: 'gdal.h
': No such file or directory
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Common
Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit
status 2
```

**Comment by sgillies** [comment]
PyPI doesn't host any binary Fiona distributions for Windows. Please see https://github.com/Toblerity/Fiona/blob/master/README.rst#windows for how to install on Windows.

**Comment by nyotta** [comment]
Thanks for the help, @sgillies!

**Comment by nyotta** [comment]
@sgillies -- It looks like I'm still having issues:

I was able to do the installation, but now it appears as if fiona cannot locate a specific module:
```
C:\Users\bnnyotta\Downloads>pip install Fiona-1.5.1-cp27-none-win32.whl
Processing c:\users\bnnyotta\downloads\fiona-1.5.1-cp27-none-win32.whl
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib
\site-packages (from Fiona==1.5.1)
Requirement already satisfied (use --upgrade to upgrade): cligj in c:\python27\l
ib\site-packages (from Fiona==1.5.1)
Requirement already satisfied (use --upgrade to upgrade): click>=3.0 in c:\pytho
n27\lib\site-packages (from cligj->Fiona==1.5.1)
Installing collected packages: Fiona

Successfully installed Fiona-1.5.1

C:\Users\bnnyotta\Downloads>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\fiona\__init__.py", line 79, in <module>
    from fiona.collection import Collection, vsi_path
  File "C:\Python27\lib\site-packages\fiona\collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.
>>>
```

**Comment by sgillies** [comment]
If I recall correctly, Gohlke's Fiona binary requires the GDAL one. Link on the same page.

I'm slowly working on official binaries for Windows in Rasterio: https://github.com/mapbox/rasterio/issues/260. When that's finished I'll do the same for Fiona. It's slow going because Windows is low-ish priority at work (we never deploy Windows servers).

**Comment by nyotta** [comment]
Thanks, @sgillies!  After installing GDAL, Fiona is functioning fine.  Thanks again for the help.

I imagine most Fiona users are not using Windows, so it's fine that creating the Windows binaries is lower on the priority list.

**Comment by clutariomark** [comment]
Having troubles in this:

    pip install Fiona-1.5.1-cp27-none-win32.whl

    Exception:
    Traceback (most recent call last):
    File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
    File "C:\Python27\lib\site-packages\pip\commands\install.py", line 279, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
    File "C:\Python27\lib\site-packages\pip\req.py", line 1198, in prepare_files
    do_download,
    File "C:\Python27\lib\site-packages\pip\req.py", line 1365, in unpack_url
    unpack_file_url(link, location, download_dir)
    File "C:\Python27\lib\site-packages\pip\download.py", line 641, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
    File "C:\Python27\lib\site-packages\pip\util.py", line 621, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
    File "C:\Python27\lib\site-packages\pip\util.py", line 491, in unzip_file
    zip = zipfile.ZipFile(zipfp)
    File "C:\Python27\lib\zipfile.py", line 793, in __init__
    self._RealGetContents()
    File "C:\Python27\lib\zipfile.py", line 835, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
    BadZipfile: File is not a zip file

**Comment by ElectronHarvester** [comment]
bump as a fiona user on windows.

**Comment by sharifulgeo** [comment]
@sgillies. what is "GDAL one"?  GDAL version 1.x?

**Comment by ElectronHarvester** [comment]
https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows  Atleast for windows
