### ISSUE TITLE
Check for FileGDB driver support from OGR

### ISSUE THREAD

**Issue by micahcochran** [Toblerity/Fiona#278]
Fiona needs to check with OGR if the FileGDB driver is installed. It reports that it supports the FileGDB driver.

```
$ fio env | grep FileGDB
FileGDB (modes 'r', 'a', 'w')
OpenFileGDB (modes 'r')
```

```
$ ogrinfo --formats | grep FileGDB
  -> "OpenFileGDB" (readonly)
```

This could also be present a problem for OpenFileGDB, if someone is using a version of GDAL of less than 1.11.

Otherwise trying to write to a FileGDB when the FileGDB driver software isn't installed causes errors like this.

```
$ fio dump global_cities_all.geojson | fio -v load gen/global.gdb --driver "FileGDB"
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/fiona/fio/cat.py", line 569, in load
    schema=schema) as dst:
  File "/usr/local/lib/python3.4/dist-packages/fiona/__init__.py", line 169, in open
    enabled_drivers=enabled_drivers)
  File "/usr/local/lib/python3.4/dist-packages/fiona/collection.py", line 150, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 734, in fiona.ogrext.WritingSession.start (fiona/ogrext.c:12921)
ValueError: Null driver
Aborted!
Exception ignored in: <bound method Collection.__del__ of <open Collection 'gen/global.gdb:global', mode 'w' at 0xb718194c>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/fiona/collection.py", line 407, in __del__
    self.__exit__(None, None, None)
  File "/usr/local/lib/python3.4/dist-packages/fiona/collection.py", line 402, in __exit__
    self.close()
  File "/usr/local/lib/python3.4/dist-packages/fiona/collection.py", line 386, in close
    self.flush()
  File "/usr/local/lib/python3.4/dist-packages/fiona/collection.py", line 375, in flush
    if self.session is not None and self.session.get_length() > 0:
  File "fiona/ogrext.pyx", line 455, in fiona.ogrext.Session.get_length (fiona/ogrext.c:8748)
ValueError: Null layer
```

I assume that the driver not being supported is what this error is telling me.   If any data is needed to replicate these I'm happy to hand over any of these files for testing.

My end goal is to have Fiona writing to a FileGDB.  (I have ESRI's FileGDB installed on another machine.)  I just think that Fiona should acting a little differently about a data type that requires additional software to be installed on the machine.

**Comment by micahcochran** [comment]
I wrote some code to filter the `supported_drivers` dictionary in _drivers.pyx based on if OGR supports the driver (using `GDALEnv.drivers()`).  I envision this to be a fix instead of just a patch for my described problem with FileGDB.

It seems that the `supported_drivers` should be a dictionary of all the drivers that Fiona supports in its current configuration.  If OGR doesn't support it, you likely get the error decribed in the above post.

Here are some ways that I have thought of to solve this:
1. One option is to move `supported_drivers` dictionary to Python (it is currently in Cython code), and put it with my code that filters the list as is (and make internal changes for imports to point to the new location).   None of the Cython code needs access to supported_drivers.  I like this option. (I'm biased because I have code seems to mostly works for this option.)
2. Another option is to do Option 1 and convert the code to Cython.  
3. Yet another option is to do OGR support detection in a way that builds is build the dictonary for `supported_drivers dictionary based on support.  This option might be easier Cython that the above approach.  This might be a little more complicated than just adding a line to the `support_drivers` dictionary.

**Comment by micahcochran** [comment]
The patch has been merged.  Closing.
