### ISSUE TITLE
reprojecting nuts2

### ISSUE THREAD

**Issue by gidden** [Toblerity/Fiona#328]
Hi all,

I'm trying to reproject a NUTS2 dataset and am getting the following error:

```
$ fio cat nuts2_2008.shp --dst_crs EPSG:4326 | fio load --format Shapefile --dst_crs EPSG:4326 output.shp
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/fiona/fio/cat.py", line 586, in load
    first = next(source)
  File "build/bdist.linux-x86_64/egg/fiona/fio/cat.py", line 577, in feature_gen
    for feat in json.loads(text)['features']:
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 311 column 1 (char 775 - 550587)
Aborted!
```

It is the `load` command that is failing here, FWIW. Any suggestions would be welcome.

**Comment by geowurster** [comment]
@gidden Looks like you probably need `$ fio load --sequence`.  `$ fio cat` produces GeoJSON features, one per line, and `$ fio load` expects a full `FeatureCollection`by default.

**Comment by gidden** [comment]
Hi @geowurster, that worked beautifully. I'll close the issue.
