### ISSUE TITLE
GDAL exception: Recode from System to UTF-8 not supported

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#481]
I'm getting the following exception when trying to open a shapefile. Passing "encoding" to `open` doesn't seem to have any effect. How do I access this file?

```
>>> src = fiona.open("lsoa_plus.shp", "r")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\envs\python36\lib\site-packages\fiona\__init__.py", line 165, in o
pen
    enabled_drivers=enabled_drivers)
  File "C:\Miniconda3\envs\python36\lib\site-packages\fiona\collection.py", line 153, in
 __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 395, in fiona.ogrext.Session.start
  File "fiona/_err.pyx", line 185, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_AppDefinedError: b'Recode from System to UTF-8 not supported, treated as
 ISO8859-1 to UTF-8.'
```

I can read the layer as expected using QGIS and `ogrinfo`.

Running Fiona 1.7.9 (from conda-forge) on Python 3.6.2.

**Comment by snorfalorpagus** [comment]
Duplicate of #455. :(
