### ISSUE TITLE
Problems reading GPX files from Fiona with valid GDAL.

### ISSUE THREAD

**Issue by ricecooker** [Toblerity/Fiona#542]
## Expected behavior and actual behavior.
pip installed fiona (1.7.11) has problems reading GPX files even with a valid GDAL/OGR setup.

Was able to workaround by downloading from source and installing from local source:
1. `wget https://github.com/Toblerity/Fiona/archive/1.7.11.tar.gz`
1. `tar zxvf 1.7.11.tar.gz`
1. `pip install cython`
1. `pip install -e Fiona-1.7.11/`

## Steps to reproduce the problem.

```
(env) enoch:~/fiona_gdal_gpx$ pip list --format=legacy | grep Fiona
Fiona (1.7.11)
(env) enoch:~/fiona_gdal_gpx$ ogrinfo --formats | grep GPX
  GPX -vector- (rw+v): GPX
(env) enoch:~/fiona_gdal_gpx$ fio info test.gpx
ERROR:Fiona:CPLE_NotSupported in b'OGR/GPX driver has not been built with read support. Expat library required'
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "/home/enoch/fiona_gdal_gpx/env/lib/python3.6/site-packages/fiona/fio/info.py", line 50, in info
    with fiona.open(input, layer=layer) as src:
  File "/home/enoch/fiona_gdal_gpx/env/lib/python3.6/site-packages/fiona/__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "/home/enoch/fiona_gdal_gpx/env/lib/python3.6/site-packages/fiona/collection.py", line 153, in __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 405, in fiona.ogrext.Session.start
  File "fiona/_err.pyx", line 185, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_NotSupportedError: b'OGR/GPX driver has not been built with read support. Expat library required'
Aborted!
(env) enoch:~/fiona_gdal_gpx$ ogrinfo test.gpx
Had to open data source read-only.
INFO: Open of `test.gpx'
      using driver `GPX' successful.
1: waypoints (Point)
2: routes (Line String)
3: tracks (Multi Line String)
4: route_points (Point)
5: track_points (Point)
(env) enoch:~/fiona_gdal_gpx$
```
## Operating system
```
(env) enoch:~/fiona_gdal_gpx$ uname -srvmpio
Linux 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
## Fiona and GDAL version and provenance
```
(env) enoch:~/fiona_gdal_gpx$ pip --version
pip 9.0.1 from /home/enoch/fiona_gdal_gpx/env/lib/python3.6/site-packages (python 3.6)
(env) enoch:~/fiona_gdal_gpx$ python -c 'import fiona; print(fiona.__version__)'
1.7.11
(env) enoch:~/fiona_gdal_gpx$ python -c 'import fiona; print(fiona.__gdal_version__)'
2.2.2
```
GDAL was built from source though I suspect the apt one is fine too.
```
(env) enoch:~/gdal-2.2.3$ ./configure | grep xpat
/bin/bash: ./config.rpath: No such file or directory
checking for XML_ParserCreate in -lexpat... yes
checking for Expat XML Parser headers in /usr/include... found
checking for Expat XML Parser... yes
checking if Expat XML Parser version is >= 1.95.0... yes
  Expat support:             yes
```

**Comment by sgillies** [comment]
@ricecooker I can't reproduce this problem. I think it's possible that you've built Fiona using a different GDAL build than you intended, and I think I see a sign that above: your `fiona.__gdal_version__` is 2.2.2 but you're looking in a `~/gdal-2.2.3` configuration for expat.

Re-installing Fiona like so `GDAL_CONFIG=$prefix/bin/gdal-config pip install -e Fiona-1.7.11/`, where `$prefix` is wherever you installed from your source at `~/gdal-2.2.3`, should do the trick.

**Comment by ricecooker** [comment]
Thanks for looking into this. I think the way I reported the issue is a bit confusing. The fiona I had problems with is the one coming straight from `pip install fiona`. The fiona straight from pip throws `ERROR:Fiona:CPLE_NotSupported in b'OGR/GPX driver has not been built with read support. Expat library required'`

`pip install -e` version works fine for me on multiple versions of gdal(tried 1.11.3 from apt, 2.2.2 and 2.2.3 from source). I was on a Ubuntu 16.04 AMI. 

My setup from vanilla Amazon Ubuntu 16.04 LTS image: 
```
sudo apt update
sudo apt install gdal-bin libgdal-dev python-gdal python3-gdal python3-venv
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install fiona
```
My test:
```
(venv) enoch@ip-xxx-xxx-xxx-xxx.ec2.internal:~$ fio info test.gpx
ERROR:Fiona:CPLE_NotSupported in b'OGR/GPX driver has not been built with read support. Expat library required'
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "/home/enoch/venv/lib/python3.5/site-packages/fiona/fio/info.py", line 50, in info
    with fiona.open(input, layer=layer) as src:
  File "/home/enoch/venv/lib/python3.5/site-packages/fiona/__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "/home/enoch/venv/lib/python3.5/site-packages/fiona/collection.py", line 153, in __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 405, in fiona.ogrext.Session.start
  File "fiona/_err.pyx", line 185, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_NotSupportedError: b'OGR/GPX driver has not been built with read support. Expat library required'
Aborted!
```

**Comment by sgillies** [comment]
Ah, yes. I've confirmed on Linux (had checked OS X previously) that I messed up the wheel. I'll schedule a 1.7.11.post1 release right away, probably by tomorrow morning.

**Comment by sgillies** [comment]
Resolved. See #545.
