### ISSUE TITLE
test_drivers.py passes when run alone, but fails when run as part of test suite.

### ISSUE THREAD

**Issue by GeoWill** [Toblerity/Fiona#622]
## Expected behavior and actual behavior.
Expected:
  - When running `py.test` and `py.test tests/test_drivers.py` test_drivers.py would pass or fail in both cases. 

Actual
  - When running `py.test tests/test_drivers.py` the test passes.
  - When running `py.test` the test fails.

Failure output:

```
____________________________________________________________________________________________ test_options _____________________________________________________________________________________________

tmpdir = local('/tmp/pytest-of-will/pytest-2/test_options0')

    def test_options(tmpdir):
        """Test that setting CPL_DEBUG=ON works"""
        logfile = str(tmpdir.mkdir('tests').join('test_options.log'))
        logger = logging.getLogger()
        logger.setLevel(logging.DEBUG)
        fh = logging.FileHandler(logfile)
        fh.setLevel(logging.DEBUG)
        logger.addHandler(fh)
    
        with fiona.drivers(CPL_DEBUG=True):
            path = os.path.join("tests", "data", "coutwildrnp.shp")
            c = fiona.open(path)
            c.close()
            with open(logfile, "r") as f:
                log = f.read()
            if fiona.gdal_version.major >= 2:
>               assert "GDALOpen" in log
E               assert 'GDALOpen' in "Creating a not-responsible GDALEnv in drivers()\nGDAL data files not located, GDAL_DATA not set\nPROJ data files not ...not set\nPROJ data files not located, PROJ_LIB not set\nSet option b'ENCODING': b''\nFlushed buffer\nStopped session\n"

tests/test_drivers.py:30: AssertionError
---------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:fiona._drivers:GDAL data files not located, GDAL_DATA not set
WARNING:fiona._drivers:PROJ data files not located, PROJ_LIB not set
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable config_file from defaults.
DEBUG:botocore.session:Loading variable credentials_file from defaults.
DEBUG:botocore.session:Loading variable data_path from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable region from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable credentials_file from defaults.
DEBUG:botocore.session:Loading variable config_file from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable metadata_service_timeout from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable metadata_service_num_attempts from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.credentials:Looking for credentials via: env
DEBUG:botocore.credentials:Looking for credentials via: assume-role
DEBUG:botocore.credentials:Looking for credentials via: shared-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: custom-process
DEBUG:botocore.credentials:Looking for credentials via: config-file
DEBUG:botocore.credentials:Looking for credentials via: ec2-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: boto-config
DEBUG:botocore.credentials:Looking for credentials via: container-role
DEBUG:botocore.credentials:Looking for credentials via: iam-role
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
DEBUG:botocore.utils:Caught exception while trying to retrieve credentials: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 139, in _new_conn
    (self.host, self.timeout))
botocore.vendored.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
botocore.vendored.requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/utils.py", line 180, in _get_request
    response = requests.get(url, timeout=timeout)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
botocore.vendored.requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
DEBUG:botocore.utils:Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
WARNING:fiona._drivers:GDAL data files not located, GDAL_DATA not set
WARNING:fiona._drivers:PROJ data files not located, PROJ_LIB not set
DEBUG:fiona._shim:Set option b'ENCODING': b''
GDAL: GDALOpen(tests/data/coutwildrnp.shp, this=0x2f7b620) succeeds as ESRI Shapefile.
DEBUG:fiona.collection:Flushed buffer
GDAL: GDALClose(tests/data/coutwildrnp.shp, this=0x2f7b620)
DEBUG:fiona.collection:Stopped session
------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------
__init__.py                361 DEBUG    Creating a not-responsible GDALEnv in drivers()
test_drivers.py             23 WARNING  GDAL data files not located, GDAL_DATA not set
test_drivers.py             23 WARNING  PROJ data files not located, PROJ_LIB not set
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable config_file from defaults.
session.py                 287 DEBUG    Loading variable credentials_file from defaults.
session.py                 287 DEBUG    Loading variable data_path from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable region from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable credentials_file from defaults.
session.py                 287 DEBUG    Loading variable config_file from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable metadata_service_timeout from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable metadata_service_num_attempts from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
credentials.py            1661 DEBUG    Looking for credentials via: env
credentials.py            1661 DEBUG    Looking for credentials via: assume-role
credentials.py            1661 DEBUG    Looking for credentials via: shared-credentials-file
credentials.py            1661 DEBUG    Looking for credentials via: custom-process
credentials.py            1661 DEBUG    Looking for credentials via: config-file
credentials.py            1661 DEBUG    Looking for credentials via: ec2-credentials-file
credentials.py            1661 DEBUG    Looking for credentials via: boto-config
credentials.py            1661 DEBUG    Looking for credentials via: container-role
credentials.py            1661 DEBUG    Looking for credentials via: iam-role
connectionpool.py          203 INFO     Starting new HTTP connection (1): 169.254.169.254
utils.py                   183 DEBUG    Caught exception while trying to retrieve credentials: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 139, in _new_conn
    (self.host, self.timeout))
botocore.vendored.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
botocore.vendored.requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/utils.py", line 180, in _get_request
    response = requests.get(url, timeout=timeout)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/will/.local/share/virtualenvs/Fiona-chaMltC8/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
botocore.vendored.requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f95cc7c8208>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
utils.py                   218 DEBUG    Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
collection.py              151 WARNING  GDAL data files not located, GDAL_DATA not set
collection.py              151 WARNING  PROJ data files not located, PROJ_LIB not set
collection.py              160 DEBUG    Set option b'ENCODING': b''
collection.py              442 DEBUG    Flushed buffer
collection.py              444 DEBUG    Stopped session
```

## Operating system

Ubuntu 16.04

## Fiona and GDAL version and provenance

Python 3.5.2, 
GDAL: 2.2.2

**Comment by sgillies** [comment]
@GeoWill sorry, a subset of the tests currently require that you have AWS credentials configured on your computer. We're working to fix this. I'll close this one as it's a known bug: https://github.com/Toblerity/Fiona/issues/507.
