### ISSUE TITLE
Fiona 1.8.0 fails to build (ValueError: 'fiona/ogrext.pyx' doesn't match any files)

### ISSUE THREAD

**Issue by sebastic** [Toblerity/Fiona#666]
The fiona Debian package build for 1.8.0 failed:
```
dh  build --with python2,python3,sphinxdoc --buildsystem pybuild
   dh_update_autotools_config -O--buildsystem=pybuild
   dh_auto_configure -O--buildsystem=pybuild
I: pybuild base:217: python2.7 setup.py config 
fiona/_transform.pyx: cannot find cimported module 'fiona'
fiona/_crs.pyx: cannot find cimported module 'fiona'
Traceback (most recent call last):
  File "setup.py", line 226, in <module>
    Extension('fiona.ogrext', ['fiona/ogrext.pyx'], **ext_options)])
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 897, in cythonize
    aliases=aliases)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 102, in nonempty
    raise ValueError(error_msg)
ValueError: 'fiona/ogrext.pyx' doesn't match any files
E: pybuild pybuild:338: configure: plugin distutils failed with: exit code=1: python2.7 setup.py config 
```

There is no `ogrext.pyx`, there are only `fiona/ogrext1.pxd` & `fiona/ogrext2.pxd`.

## Steps to reproduce the problem.

Build fiona on Debian unstable.

## Operating system

Debian unstable

## Fiona and GDAL version and provenance

Fiona 1.8.0 with GDAL 2.3.2 from Debian unstable.

**Comment by sebastic** [comment]
Looks like the package removes `fiona/ogrext.pyx` in the clean target for some reason.

**Comment by sebastic** [comment]
Thanks for the feedback, but no help is needed. The package has been updated to not remove the `.pyx` file in the clean target.
