### ISSUE TITLE
Import GeoPandas throws error with Fiona?Jupyter Notebook

### ISSUE THREAD

**Issue by LiamLav5** [Toblerity/Fiona#682]
Hi,
I have tried for hours reinstalling GeoPandas, reinstalling anaconda, Jupyter notebook etc and cannot solve this issue. 
I am running Jupyter notebook and I am trying to import GeoPandas after installing. I get this error:
```
---
ImportError                               Traceback (most recent call last)
<ipython-input-2-a62d01c1d62e> in <module>
----> 1 import geopandas as gpd

/anaconda3/envs/new/lib/python3.7/site-packages/geopandas/__init__.py in <module>
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

/anaconda3/envs/new/lib/python3.7/site-packages/geopandas/io/file.py in <module>
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 import six

/anaconda3/envs/new/lib/python3.7/site-packages/fiona/__init__.py in <module>
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/anaconda3/envs/new/lib/python3.7/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: dlopen(/anaconda3/envs/new/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libkea.1.4.7.dylib
  Referenced from: /anaconda3/envs/new/lib/libgdal.20.dylib
  Reason: image not found
```

Conda List:
```
# packages in environment at /anaconda3/envs/new:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0                    py37_0  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    3.0.2                    py37_0  
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
certifi                   2018.10.15            py37_1000    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py37_0  
descartes                 1.1.0                      py_2    conda-forge
entrypoints               0.2.3                    py37_2  
expat                     2.2.6                h0a44026_0  
fiona                     1.7.13           py37hb00a9d7_3    conda-forge
fontconfig                2.13.1               hce039c3_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.2.4            py37h6440ff4_1  
geopandas                 0.4.0                      py_1    conda-forge
geos                      3.6.2                hfc679d8_3    conda-forge
gettext                   0.19.8.1             h15daf44_3  
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.56.2               hd9629dc_0  
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.0                      118  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.1.1            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
jedi                      0.13.1                   py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   he5867d9_2  
json-c                    0.13.1               h470a237_1    conda-forge
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.3                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1            py37h2d50403_2    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libdap4                   3.19.1               h18059cb_1    conda-forge
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgdal                   2.2.4                h7b1ea53_1  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1                h5e45101_3    conda-forge
libpng                    1.6.35               ha441bb4_0  
libpq                     10.5                 hf16a0db_0    conda-forge
libsodium                 1.0.16               h3efe00b_0  
libspatialindex           1.8.5                hfc679d8_3    conda-forge
libspatialite             4.3.0a              ha12ebda_19  
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
markupsafe                1.0              py37h1de35cc_1  
matplotlib                2.2.3            py37h0e0179f_0    conda-forge
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.0                      118  
mkl_fft                   1.0.4            py37h5d10147_1  
mkl_random                1.0.1            py37h5d10147_1  
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.3.1                    py37_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_0  
notebook                  5.7.0                    py37_0  
numpy                     1.15.1           py37h6a91979_0  
numpy-base                1.15.1           py37h8a80b8c_0  
openjpeg                  2.3.0                h316dc23_3    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pandas                    0.23.4           py37h6440ff4_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.3.1                    py37_0  
pcre                      8.42                 h378b8a2_0  
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pip                       10.0.1                   py37_0  
pixman                    0.34.0               h470a237_3    conda-forge
poppler                   0.65.0               ha097c24_1  
poppler-data              0.4.9                         0    conda-forge
proj4                     5.0.1                         0    conda-forge
prometheus_client         0.4.2                    py37_0  
prompt_toolkit            2.0.7                    py37_0  
psycopg2                  2.7.6.1          py37hdffb7b8_0    conda-forge
ptyprocess                0.6.0                    py37_0  
pygments                  2.2.0                    py37_0  
pyparsing                 2.3.0                      py_0    conda-forge
pyproj                    1.9.5.1          py37h833a5d7_1  
pyqt                      5.9.2            py37h655552a_2  
pysal                     1.14.4.post2          py37_1001    conda-forge
python                    3.7.1                h46c1a51_0    conda-forge
python-dateutil           2.7.3                    py37_0  
pytz                      2018.5                   py37_0  
pyzmq                     17.1.2           py37h1de35cc_0  
qt                        5.9.6                h45cd832_2  
qtconsole                 4.4.2                    py37_0  
readline                  7.0                  h1de35cc_5  
rtree                     0.8.3                 py37_1000    conda-forge
scipy                     1.1.0            py37h28f7352_1  
send2trash                1.5.0                    py37_0  
setuptools                40.2.0                   py37_0  
shapely                   1.6.4            py37h164cb2d_0    conda-forge
sip                       4.19.8           py37h0a44026_0  
six                       1.11.0                   py37_1  
sqlalchemy                1.2.14           py37h470a237_0    conda-forge
sqlite                    3.25.3               ha441bb4_0  
terminado                 0.8.1                    py37_1  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
tornado                   5.1.1            py37h1de35cc_0  
traitlets                 4.3.2                    py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.31.1                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
xerces-c                  3.2.2                h5d6a6da_0    conda-forge
xz                        5.2.4                h1de35cc_4  
zeromq                    4.2.5                h0a44026_1  
zlib                      1.2.11               hf3cbc9b_2    
```

**Comment by LiamLav5** [comment]
@ocefpaf Hi, I was running Conda list for the wrong environment. I updated the post to the new list

**Comment by ocefpaf** [comment]
> @ocefpaf Hi, I was running Conda list for the wrong environment. I updated the post to the new list

Yep. Now we can see that the real problem is a bad mix of `conda-forge` and `defaults`. Please read https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels for more info.

My recommendation is to remove `defaults` (or `conda-forge`) from your configuration and rely on a single channel to obtain your packages.

**Comment by LiamLav5** [comment]
@ocefpaf What are the steps for me to go about doing this? Basically I am trying to get my Jupyter  notebook running and it requires GeoPandas for some of the cells. Do I need to create a new environment ?

**Comment by ocefpaf** [comment]
This is what I would do:

```shell
conda config --remove channels defaults
conda create --name MY_ENV_NAME python=3.7 fiona jupyter # (and all the other packages you will use)
conda activate MY_ENV_NAME
```

You can also create a `environment.yml` file for the env instead of listing them in the CLI.

**Comment by AntjeGaertner** [comment]
I can not use Geopandas when I install an Iphython kernel in my environment. When I form my environment like this:
`conda create -n GIS python=3.6 geopandas=0.4.0 gdal=2.2.4`
I can import Fiona and geopandas into python.

However, when I then install an iphython kernel to use geopandas in a Jupyter notebook it does not work any longer. I then get this error:
`>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/antje/anaconda/envs/GIS/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/antje/anaconda/envs/GIS/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/antje/anaconda/envs/GIS/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/antje/anaconda/envs/GIS/lib/libgdal.20.dylib
  Reason: image not found
`

I have used Geopandas previously in a jupyter notebook but now I have the resetup the environment. Which package is crushing my import of Geopandas here? Does anyone now? Or the last stable version of Iphyton + kernel and jupyter with Geopandas?

**Comment by mmaari** [comment]
HI! 
I am relatively new to Python and GeoPandas. I am having the same issue importing the package. 
I have created an environment with only conda-forge packages, installed fiona and geopandas in there and working in the environment on Jupyter Notebook. I still get the same error message when I do 
```
import geopandas as gpd 
```
Namely, the error message is this: 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a62d01c1d62e> in <module>
----> 1 import geopandas as gpd

~/anaconda3/lib/python3.7/site-packages/geopandas/__init__.py in <module>
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

~/anaconda3/lib/python3.7/site-packages/geopandas/io/file.py in <module>
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 import six

~/anaconda3/lib/python3.7/site-packages/fiona/__init__.py in <module>
     81     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     82 
---> 83 from fiona.collection import BytesCollection, Collection
     84 from fiona.drvsupport import supported_drivers
     85 from fiona.env import ensure_env_with_credentials, Env

~/anaconda3/lib/python3.7/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libgif.7.dylib
  Referenced from: /anaconda3/lib/libgdal.20.dylib
  Reason: image not found
```

and when running conda list I get this: 

```
# packages in environment at /anaconda3/envs/env2:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            h9247486_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
descartes                 1.1.0                      py_3    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
fiona                     1.8.6            py37h7eb7563_2    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      2.4.1            py37h7eb7563_0    conda-forge
geopandas                 0.4.1                      py_1    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.4.3             hce09ea4_1000    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h2836805_1001    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            hecf890f_1003    conda-forge
kiwisolver                1.0.1           py37h04f5b5a_1002    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.1                h16bfee5_0    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             h71ee1b2_1009    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libpq                     11.2                 h29c6f28_0    conda-forge
libspatialindex           1.9.0                h6de7cb9_0    conda-forge
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            h344961e_1002    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
mapclassify               2.0.1                      py_0    conda-forge
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37hf043ca5_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.2           py37hbb3c62a_1    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
pandas                    0.24.2           py37h0a44026_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
poppler                   0.67.0               hb974355_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h16efa30_0    conda-forge
proj4                     5.2.0             h1de35cc_1001    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py37h9c430a6_1000    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
setuptools                41.0.0                   py37_0    conda-forge
shapely                   1.6.4           py37h4b8df73_1003    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1001    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
tornado                   6.0.2            py37h01d97ff_0    conda-forge
tzcode                    2018g             h1de35cc_1001    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xerces-c                  3.2.2             h44e365a_1001    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.3.3                         1    conda-forge
```

I am using  macOS Mojave version 10.14.3

Anyone knows how to help me? I would be very grateful! 

Thank you!

**Comment by ocefpaf** [comment]
@mmaari this is an old, and closed issue, about the conda package. Because you are using conda-forge I recommend you to open a new issue in https://github.com/conda-forge/fiona-feedstock/issues.

**Comment by AntjeGaertner** [comment]
@mmaari I had the same issue a month ago. I solved it be installing specific version of geopandas and some other packages. I would not know how to do it for the updated versions. but this list of packages runs smoothly together:

conda create -n GIS python=3.6 geopandas=0.4.0 gdal=2.2.4 ipykernel=4.8.2 jupyter geoplot=0.1.2
