### ISSUE TITLE
S3 read GPKG pragma foreign_key_check fail

### ISSUE THREAD

**Issue by mccarthyryanc** [Toblerity/Fiona#699]
I'm trying to read a GPKG from S3:
```python
import fiona
ds = fiona.open('s3://bucketname/filename.gpkg')
```
but get the following DriverError:
```
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 66, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 259, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_AppDefinedError: pragma foreign_key_check on '/vsis3/bucketname/filename.gpkg' failed. You can disable this check by setting the OGR_GPKG_FOREIGN_KEY_CHECK configuration option to NO

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda/envs/fiona-env/lib/python3.6/site-packages/fiona/env.py", line 405, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/fiona-env/lib/python3.6/site-packages/fiona/__init__.py", line 253, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/home/ubuntu/miniconda/envs/fiona-env/lib/python3.6/site-packages/fiona/collection.py", line 159, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 467, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 73, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: pragma foreign_key_check on '/vsis3/bucketname/filename.gpkg' failed. You can disable this check by setting the OGR_GPKG_FOREIGN_KEY_CHECK configuration option to NO
```

Is this a bug, or is there are way to provide this config option to fiona? I seem to remember `fiona.drivers` accepting config options, but it looks like that is deprecated.

## System Setup

Ubuntu 18.04, python 3.6, GDAL 2.3.2, fiona 1.8.4.

I installed gdal via conda and fiona via pip:

```bash
conda create -n fiona-env python=3.6 gdal
conda activate fiona-env
pip install git+https://github.com/Toblerity/Fiona.git
```

**Comment by mccarthyryanc** [comment]
Ah! `fiona.Env` was what I wanted, plus the AWSSession because I'm running this on an EC2 instance. Here is what I got working:
```python
import fiona
from fiona.session import AWSSession

with fiona.Env(OGR_GPKG_FOREIGN_KEY_CHECK='NO', session=AWSSession()):
    ds = fiona.open('s3://wy-tl-lidar/ATLC18/ATLC18.gpkg')
```

However, is this the expected behavior? Or is there perhaps something wrong with my GPKG?

**Comment by mccarthyryanc** [comment]
Ah! `fiona.Env` was what I wanted, plus the AWSSession because I'm running this on an EC2 instance. Here is what I got working:
```python
import fiona
from fiona.session import AWSSession

with fiona.Env(OGR_GPKG_FOREIGN_KEY_CHECK='NO', session=AWSSession()):
    ds = fiona.open('s3://bucketname/filename.gpkg')
```

However, is this the expected behavior? Or is there perhaps something wrong with my GPKG?
