### ISSUE TITLE
How to read files with mask?

### ISSUE THREAD

**Issue by culebron** [Toblerity/Fiona#707]
Hi,
I could not find anything with Google on this question.

Here's the code where I try to use mask on opened file, but it does not work. I did it with GPKG, but for a reproducible demo, it's GeoJSON. With GPKG the exception is the same.

I try both with start/stop, and without.

	import fiona
	import geopandas as gpd
	blocks = gpd.read_file('block.geojson', driver='GeoJSON')['geometry'].tolist()

	handler = fiona.open('points.geojson', driver='GeoJSON')
	try:
		filtered = handler.filter(mask=blocks)
	except Exception as e:
		print(e)
		print('=====')

	filtered = handler.filter(mask=blocks, start=0, stop=1000, step=1)

	iterator = iter(handler)
	for row in iterator:
		print(row)

Output:

	list indices must be integers or slices, not str
	=====
	Traceback (most recent call last):
	  File "test_fiona.py", line 12, in <module>
	    filtered = handler.filter(mask=blocks, start=0, stop=1000, step=1)
	  File "/usr/local/lib/python3.6/dist-packages/fiona/collection.py", line 261, in filter
	    self, start, stop, step, bbox, mask)
	  File "fiona/ogrext.pyx", line 1257, in fiona.ogrext.Iterator.__cinit__
	  File "fiona/_geometry.pyx", line 266, in fiona._geometry.OGRGeomBuilder.build
	TypeError: list indices must be integers or slices, not str

Fiona version is `1.8.4` (just reinstalled with `--no-binary` option).
Data files and how it looks like (I expect to read only those two points inside the block):

![selection_009](https://user-images.githubusercontent.com/119675/50968199-e8246180-150c-11e9-919b-6f1b7f825bb7.png)

**block.geojson**:

    {"type": "FeatureCollection", "name": "block", "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 44.008052, 56.32239 ], [ 44.008042, 56.322381 ], [ 44.004346, 56.322169 ], [ 44.004333, 56.322177 ], [ 44.004693, 56.322955 ], [ 44.004703, 56.32296 ], [ 44.007532, 56.323235 ], [ 44.007547, 56.32323 ], [ 44.008052, 56.32239 ] ] ] } }]}

**points.geojson**:

	{
	"type": "FeatureCollection",
	"name": "points",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
	"features": [
	{ "type": "Feature", "properties": { "fid": 1 }, "geometry": { "type": "Point", "coordinates": [ 44.008454120594898, 56.317177503444697 ] } },
	{ "type": "Feature", "properties": { "fid": 2 }, "geometry": { "type": "Point", "coordinates": [ 44.0071848988892, 56.316891541379803 ] } },
	{ "type": "Feature", "properties": { "fid": 3 }, "geometry": { "type": "Point", "coordinates": [ 44.007353467397003, 56.316682567747399 ] } },
	{ "type": "Feature", "properties": { "fid": 4 }, "geometry": { "type": "Point", "coordinates": [ 44.008454120594898, 56.316902539960402 ] } },
	{ "type": "Feature", "properties": { "fid": 5 }, "geometry": { "type": "Point", "coordinates": [ 44.007442709548201, 56.317430468101598 ] } },
	{ "type": "Feature", "properties": { "fid": 6 }, "geometry": { "type": "Point", "coordinates": [ 44.003962265652198, 56.317391973588002 ] } },
	{ "type": "Feature", "properties": { "fid": 7 }, "geometry": { "type": "Point", "coordinates": [ 44.003149170496997, 56.317248993626301 ] } },
	{ "type": "Feature", "properties": { "fid": 8 }, "geometry": { "type": "Point", "coordinates": [ 44.002851696659803, 56.317122510906202 ] } },
	{ "type": "Feature", "properties": { "fid": 9 }, "geometry": { "type": "Point", "coordinates": [ 44.003327654799399, 56.316418599419301 ] } },
	{ "type": "Feature", "properties": { "fid": 10 }, "geometry": { "type": "Point", "coordinates": [ 44.003565633869201, 56.316033642336599 ] } },
	{ "type": "Feature", "properties": { "fid": 11 }, "geometry": { "type": "Point", "coordinates": [ 44.0050926662338, 56.316336108942501 ] } },
	{ "type": "Feature", "properties": { "fid": 12 }, "geometry": { "type": "Point", "coordinates": [ 43.998092115263603, 56.3196520857108 ] } },
	{ "type": "Feature", "properties": { "fid": 13 }, "geometry": { "type": "Point", "coordinates": [ 43.998974620980803, 56.320383431544798 ] } },
	{ "type": "Feature", "properties": { "fid": 14 }, "geometry": { "type": "Point", "coordinates": [ 44.0000256952058, 56.320410925475898 ] } },
	{ "type": "Feature", "properties": { "fid": 15 }, "geometry": { "type": "Point", "coordinates": [ 44.0002835058648, 56.3206803649527 ] } },
	{ "type": "Feature", "properties": { "fid": 16 }, "geometry": { "type": "Point", "coordinates": [ 43.999886874081803, 56.3206803649527 ] } },
	{ "type": "Feature", "properties": { "fid": 17 }, "geometry": { "type": "Point", "coordinates": [ 44.000075274178698, 56.321054277811299 ] } },
	{ "type": "Feature", "properties": { "fid": 18 }, "geometry": { "type": "Point", "coordinates": [ 44.001770875051101, 56.321213739534201 ] } },
	{ "type": "Feature", "properties": { "fid": 19 }, "geometry": { "type": "Point", "coordinates": [ 44.001641969721597, 56.321901066924703 ] } },
	{ "type": "Feature", "properties": { "fid": 20 }, "geometry": { "type": "Point", "coordinates": [ 43.999519989682497, 56.321609641622103 ] } },
	{ "type": "Feature", "properties": { "fid": 21 }, "geometry": { "type": "Point", "coordinates": [ 43.999301842201803, 56.321356704650597 ] } },
	{ "type": "Feature", "properties": { "fid": 22 }, "geometry": { "type": "Point", "coordinates": [ 43.999024199953702, 56.321098267318597 ] } },
	{ "type": "Feature", "properties": { "fid": 23 }, "geometry": { "type": "Point", "coordinates": [ 43.999252263228897, 56.321318214095001 ] } },
	{ "type": "Feature", "properties": { "fid": 24 }, "geometry": { "type": "Point", "coordinates": [ 44.005608287551802, 56.320669367460297 ] } },
	{ "type": "Feature", "properties": { "fid": 25 }, "geometry": { "type": "Point", "coordinates": [ 44.0038829392956, 56.3206803649527 ] } },
	{ "type": "Feature", "properties": { "fid": 26 }, "geometry": { "type": "Point", "coordinates": [ 44.004200244722099, 56.321158752808401 ] } },
	{ "type": "Feature", "properties": { "fid": 27 }, "geometry": { "type": "Point", "coordinates": [ 44.004309318462397, 56.321670126301797 ] } },
	{ "type": "Feature", "properties": { "fid": 28 }, "geometry": { "type": "Point", "coordinates": [ 44.004408476408102, 56.321862576917901 ] } },
	{ "type": "Feature", "properties": { "fid": 29 }, "geometry": { "type": "Point", "coordinates": [ 44.004616708094197, 56.322071522202798 ] } },
	{ "type": "Feature", "properties": { "fid": 30 }, "geometry": { "type": "Point", "coordinates": [ 44.006520540652701, 56.322175994416398 ] } },
	{ "type": "Feature", "properties": { "fid": 31 }, "geometry": { "type": "Point", "coordinates": [ 44.0074922885211, 56.322230979677201 ] } },
	{ "type": "Feature", "properties": { "fid": 32 }, "geometry": { "type": "Point", "coordinates": [ 44.006827930284501, 56.3224454214376 ] } },
	{ "type": "Feature", "properties": { "fid": 33 }, "geometry": { "type": "Point", "coordinates": [ 44.003972181446798, 56.322318955929703 ] } },
	{ "type": "Feature", "properties": { "fid": 34 }, "geometry": { "type": "Point", "coordinates": [ 44.004220076311199, 56.3225169017567 ] } },
	{ "type": "Feature", "properties": { "fid": 35 }, "geometry": { "type": "Point", "coordinates": [ 44.004101086776302, 56.322522400237197 ] } },
	{ "type": "Feature", "properties": { "fid": 36 }, "geometry": { "type": "Point", "coordinates": [ 44.003694539198698, 56.323022758651902 ] } },
	{ "type": "Feature", "properties": { "fid": 37 }, "geometry": { "type": "Point", "coordinates": [ 44.005925592978201, 56.3226873542853 ] } },
	{ "type": "Feature", "properties": { "fid": 38 }, "geometry": { "type": "Point", "coordinates": [ 44.007155151505501, 56.324837190203297 ] } },
	{ "type": "Feature", "properties": { "fid": 39 }, "geometry": { "type": "Point", "coordinates": [ 44.007750099180001, 56.325139587078098 ] } },
	{ "type": "Feature", "properties": { "fid": 40 }, "geometry": { "type": "Point", "coordinates": [ 44.0083847100329, 56.324496303581597 ] } },
	{ "type": "Feature", "properties": { "fid": 41 }, "geometry": { "type": "Point", "coordinates": [ 44.0077897623583, 56.3250736097824 ] } },
	{ "type": "Feature", "properties": { "fid": 42 }, "geometry": { "type": "Point", "coordinates": [ 44.007581530672297, 56.325238552807697 ] } },
	{ "type": "Feature", "properties": { "fid": 43 }, "geometry": { "type": "Point", "coordinates": [ 44.0083450468546, 56.324435823379098 ] } },
	{ "type": "Feature", "properties": { "fid": 44 }, "geometry": { "type": "Point", "coordinates": [ 44.008007909839002, 56.324358848437498 ] } },
	{ "type": "Feature", "properties": { "fid": 45 }, "geometry": { "type": "Point", "coordinates": [ 44.007710436001702, 56.3243643466527 ] } },
	{ "type": "Feature", "properties": { "fid": 46 }, "geometry": { "type": "Point", "coordinates": [ 44.007155151505501, 56.3243478520046 ] } },
	{ "type": "Feature", "properties": { "fid": 47 }, "geometry": { "type": "Point", "coordinates": [ 44.006629614392999, 56.324309364464398 ] } },
	{ "type": "Feature", "properties": { "fid": 48 }, "geometry": { "type": "Point", "coordinates": [ 44.0074526253428, 56.324061943637098 ] } },
	{ "type": "Feature", "properties": { "fid": 49 }, "geometry": { "type": "Point", "coordinates": [ 44.007819509742099, 56.324155413915904 ] } },
	{ "type": "Feature", "properties": { "fid": 50 }, "geometry": { "type": "Point", "coordinates": [ 44.008186394141397, 56.324177406889397 ] } },
	{ "type": "Feature", "properties": { "fid": 51 }, "geometry": { "type": "Point", "coordinates": [ 44.0086821838701, 56.324199399850301 ] } },
	{ "type": "Feature", "properties": { "fid": 52 }, "geometry": { "type": "Point", "coordinates": [ 44.007531951699399, 56.324094933173399 ] } },
	{ "type": "Feature", "properties": { "fid": 53 }, "geometry": { "type": "Point", "coordinates": [ 44.008305383676301, 56.323479123795501 ] } },
	{ "type": "Feature", "properties": { "fid": 54 }, "geometry": { "type": "Point", "coordinates": [ 44.009475447436202, 56.324023455808799 ] } },
	{ "type": "Feature", "properties": { "fid": 55 }, "geometry": { "type": "Point", "coordinates": [ 44.009356457901198, 56.3241389191775 ] } },
	{ "type": "Feature", "properties": { "fid": 56 }, "geometry": { "type": "Point", "coordinates": [ 44.009212678879898, 56.324254382196898 ] } },
	{ "type": "Feature", "properties": { "fid": 57 }, "geometry": { "type": "Point", "coordinates": [ 44.009262257852797, 56.324229640150698 ] } },
	{ "type": "Feature", "properties": { "fid": 58 }, "geometry": { "type": "Point", "coordinates": [ 44.009237468366301, 56.324287371566903 ] } },
	{ "type": "Feature", "properties": { "fid": 59 }, "geometry": { "type": "Point", "coordinates": [ 44.008930078734501, 56.3245347909332 ] } },
	{ "type": "Feature", "properties": { "fid": 60 }, "geometry": { "type": "Point", "coordinates": [ 44.001865075099502, 56.3211779981714 ] } },
	{ "type": "Feature", "properties": { "fid": 61 }, "geometry": { "type": "Point", "coordinates": [ 44.001865075099502, 56.321232984869503 ] } },
	{ "type": "Feature", "properties": { "fid": 62 }, "geometry": { "type": "Point", "coordinates": [ 44.001845243510402, 56.3211972435248 ] } },
	{ "type": "Feature", "properties": { "fid": 63 }, "geometry": { "type": "Point", "coordinates": [ 44.0018105382294, 56.3211779981714 ] } },
	{ "type": "Feature", "properties": { "fid": 64 }, "geometry": { "type": "Point", "coordinates": [ 44.0018204540239, 56.321216488868401 ] } },
	{ "type": "Feature", "properties": { "fid": 65 }, "geometry": { "type": "Point", "coordinates": [ 43.928250216171797, 56.287420474065101 ] } },
	{ "type": "Feature", "properties": { "fid": 66 }, "geometry": { "type": "Point", "coordinates": [ 43.928289879350103, 56.2874149705302 ] } },
	{ "type": "Feature", "properties": { "fid": 67 }, "geometry": { "type": "Point", "coordinates": [ 43.928369205706701, 56.287453495257502 ] } },
	{ "type": "Feature", "properties": { "fid": 68 }, "geometry": { "type": "Point", "coordinates": [ 43.928250216171797, 56.287431481132401 ] } },
	{ "type": "Feature", "properties": { "fid": 69 }, "geometry": { "type": "Point", "coordinates": [ 43.928289879350103, 56.287458998786697 ] } },
	{ "type": "Feature", "properties": { "fid": 70 }, "geometry": { "type": "Point", "coordinates": [ 43.928299795144703, 56.287464502315203 ] } },
	{ "type": "Feature", "properties": { "fid": 71 }, "geometry": { "type": "Point", "coordinates": [ 43.928398953090401, 56.287425977599099 ] } },
	{ "type": "Feature", "properties": { "fid": 72 }, "geometry": { "type": "Point", "coordinates": [ 43.928329542528402, 56.287392956383002 ] } },
	{ "type": "Feature", "properties": { "fid": 73 }, "geometry": { "type": "Point", "coordinates": [ 43.9275263631678, 56.286539898413302 ] } },
	{ "type": "Feature", "properties": { "fid": 74 }, "geometry": { "type": "Point", "coordinates": [ 43.9275065315787, 56.286545402074204 ] } },
	{ "type": "Feature", "properties": { "fid": 75 }, "geometry": { "type": "Point", "coordinates": [ 43.927476784194901, 56.286528891089297 ] } },
	{ "type": "Feature", "properties": { "fid": 76 }, "geometry": { "type": "Point", "coordinates": [ 43.9275065315787, 56.2864848617617 ] } },
	{ "type": "Feature", "properties": { "fid": 77 }, "geometry": { "type": "Point", "coordinates": [ 43.927466868400302, 56.286451839732599 ] } },
	{ "type": "Feature", "properties": { "fid": 78 }, "geometry": { "type": "Point", "coordinates": [ 43.932097544467098, 56.289192571081401 ] } },
	{ "type": "Feature", "properties": { "fid": 79 }, "geometry": { "type": "Point", "coordinates": [ 43.929499606288303, 56.288064382171797 ] } },
	{ "type": "Feature", "properties": { "fid": 80 }, "geometry": { "type": "Point", "coordinates": [ 43.932424765687998, 56.289819939776599 ] } },
	{ "type": "Feature", "properties": { "fid": 81 }, "geometry": { "type": "Point", "coordinates": [ 43.931829818013497, 56.287447991727397 ] } },
	{ "type": "Feature", "properties": { "fid": 82 }, "geometry": { "type": "Point", "coordinates": [ 43.930867985939699, 56.287695649796703 ] } },
	{ "type": "Feature", "properties": { "fid": 83 }, "geometry": { "type": "Point", "coordinates": [ 43.926827299650199, 56.282921069909399 ] } },
	{ "type": "Feature", "properties": { "fid": 84 }, "geometry": { "type": "Point", "coordinates": [ 43.927263594611603, 56.283581566063297 ] } },
	{ "type": "Feature", "properties": { "fid": 85 }, "geometry": { "type": "Point", "coordinates": [ 43.9276602263946, 56.283807232967398 ] } },
	{ "type": "Feature", "properties": { "fid": 86 }, "geometry": { "type": "Point", "coordinates": [ 43.919112811470598, 56.282111946571703 ] } },
	{ "type": "Feature", "properties": { "fid": 87 }, "geometry": { "type": "Point", "coordinates": [ 43.922940308176699, 56.285535467048803 ] } },
	{ "type": "Feature", "properties": { "fid": 88 }, "geometry": { "type": "Point", "coordinates": [ 43.922355276296699, 56.288006595989799 ] } },
	{ "type": "Feature", "properties": { "fid": 89 }, "geometry": { "type": "Point", "coordinates": [ 43.919370622129499, 56.289531021261801 ] } },
	{ "type": "Feature", "properties": { "fid": 90 }, "geometry": { "type": "Point", "coordinates": [ 43.913867356140202, 56.292310051694201 ] } },
	{ "type": "Feature", "properties": { "fid": 91 }, "geometry": { "type": "Point", "coordinates": [ 43.913817777167303, 56.291875325611102 ] } }
	]
	}

**Comment by culebron** [comment]
Looking at the traceback, the exception happens here: https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext.pyx#L1248

**Comment by culebron** [comment]
Looking deeper in the source, I see it expects GeoJSON object as well:
https://github.com/Toblerity/Fiona/blob/master/fiona/_geometry.pyx#L266

If I get this working, will probably make a documentation pull request.
