### ISSUE TITLE
error while saving geodataframe as mapinfo .tab file 

### ISSUE THREAD

**Issue by Manikandankasi01** [Toblerity/Fiona#748]
Hi,

I'm getting below error while exporting geopandas dataframe as mapinfo .TAB file.

Code:

import geopandas as gpd

p=r"D:\data.TAB"
testdata = gpd.read_file(p)
testdata.to_file("output.TAB", driver="MapInfo File")`

Error Details :
(base) D:\FTTC_Automation\Python\PC_Check\fttc_app>python test.py
Traceback (most recent call last):
  File "fiona\ogrext.pyx", line 1167, in fiona.ogrext.WritingSession.start
  File "fiona\_err.pyx", line 246, in fiona._err.exc_wrap_int
fiona._err.CPLE_AppDefinedError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list fiel
d types.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    cable.to_file("output.TAB", driver="MapInfo File")
  File "C:\ProgramData\Anaconda3\lib\site-packages\geopandas\geodataframe.py", line 413, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\geopandas\io\file.py", line 116, in to_file
    schema=schema, **kwargs) as colxn:
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\env.py", line 397, in wrapper
    return f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\__init__.py", line 267, in open
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 1173, in fiona.ogrext.WritingSession.start
fiona.errors.SchemaError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types

Python Version:
Python3.7.3
geopandas 0.4

PFB for reproducible code.

`%matplotlib inline
from shapely.geometry import Point
from geopandas import datasets, GeoDataFrame, read_file
from geopandas.tools import overlay

zippath = datasets.get_path('nybb')
polydf = read_file(zippath)

b = [int(x) for x in polydf.total_bounds]
N = 10
polydf2 = GeoDataFrame([
{'geometry': Point(x, y).buffer(10000), 'value1': x + y, 'value2': x - y}
for x, y in zip(range(b[0], b[2], int((b[2] - b[0]) / N)),
range(b[1], b[3], int((b[3] - b[1]) / N)))])

polydf2.to_file("output.TAB", driver="MapInfo File")`

Any help on this much appreciated.

Thanks,
Mani

**Comment by sgillies** [comment]
@Manikandankasi01 it looks to me that you are misusing the DataFrame constructor. My understanding from http://geopandas.org/gallery/create_geopandas_from_pandas.html#sphx-glr-gallery-create-geopandas-from-pandas-py is that it takes a dict, not a list. Something like

```
GeoDataFrame({'geometry': [Point(x, y).buffer(10000) for x, y in zip(range(b[0], b[2], int((b[2] - b[0]) / N)), range(b[1], b[3], int((b[3] - b[1]) / N)))], 'value1': [x + y for x, y in zip(range(b[0], b[2], int((b[2] - b[0]) / N)), range(b[1], b[3], int((b[3] - b[1]) / N)))], ... })
```

At any rate, this is not a Fiona bug.

**Comment by Baron-K** [comment]
Sorry to drag this one back up, but this seems to be the only place addressing this issue (along with the same error in the geopandas github https://github.com/geopandas/geopandas/issues/967 )

I used the DataFrame constructor as exampled in your link.

code:
`
import pandas as pd
import geopandas as gpd

df = pd.DataFrame({'Nbr': ['One', 'Two', 'Three'],
                     'Amt': [1, 2, 3],
                     'lat': [0.0, 0.0, 0.0],
                     'lon': [0.0, 0.0, 0.0]})

test = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.lon, df.lat))

test.to_file('G:/test.tab', driver='MapInfo File')
`
The above will error with:
Traceback (most recent call last):
  File "fiona\ogrext.pyx", line 1133, in fiona.ogrext.WritingSession.start
  File "fiona\_err.pyx", line 246, in fiona._err.exc_wrap_int
fiona._err.CPLE_AppDefinedError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Shared\Public\PyCharm\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Shared\Public\PyCharm\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Shared\Public\PyCharm\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Shared\Public\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/aa09070/.PyCharmCE2019.1/config/scratches/scratch_1.py", line 12, in <module>
    test.to_file('G:/test.tab', driver='MapInfo File')
  File "G:\GMpy\venv\lib\site-packages\geopandas\geodataframe.py", line 515, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "G:\GMpy\venv\lib\site-packages\geopandas\io\file.py", line 128, in to_file
    filename, "w", driver=driver, crs=df.crs, schema=schema, **kwargs
  File "G:\GMpy\venv\lib\site-packages\fiona\env.py", line 398, in wrapper
    return f(*args, **kwargs)
  File "G:\GMpy\venv\lib\site-packages\fiona\__init__.py", line 267, in open
    **kwargs)
  File "G:\GMpy\venv\lib\site-packages\fiona\collection.py", line 157, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 1139, in fiona.ogrext.WritingSession.start
fiona.errors.SchemaError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types. 

However, if I change the Amt values to float, i.e 1.0, 2.0, 3.0 (or even just change 1 of the values to float), it does not error when writing the MapInfo File.
 New code:
df = pd.DataFrame({'Nbr': ['One', 'Two', 'Three'],
                     'Amt': [**1.0**, 2, 3],
                     'lat': [0.0, 0.0, 0.0],
                     'lon': [0.0, 0.0, 0.0]})

Hope this helps.
