### ISSUE TITLE
Enabling GRASS support in Fiona

### ISSUE THREAD

**Issue by epifanio** [Toblerity/Fiona#756]
## Expected behavior and actual behavior.

 I expected to be able to read `GRASS` vector datasets, as my `GDAL` version supports it.

## Steps to reproduce the problem.
* I'm using `GDAL` installed from ubuntuGIS PPA which has prebuilt GRASS plugins. 
From a `python3` environment I can successfully read `GRASS` vector datasets using the python GDAL bindings:

``` 
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ogr 
   ...: cnt = ogr.GetDriverCount() 
   ...: formatsList = []  # Empty List 
   ...:  
   ...: for i in range(cnt): 
   ...:     driver = ogr.GetDriver(i) 
   ...:     driverName = driver.GetName() 
   ...:     if not driverName in formatsList: 
   ...:         formatsList.append(driverName) 
   ...:  
   ...: formatsList.sort() # Sorting the messy list of ogr drivers 
   ...:  
   ...: for i in formatsList: 
   ...:     print(i) 
   ...:                                                                                                                                                                         
ARCGEN
AVCBin
AVCE00
AeronavFAA
AmigoCloud
BNA
CAD
CSV
CSW
Carto
Cloudant
CouchDB
DGN
DXF
EDIGEO
EEDA
ESRI Shapefile
ESRIJSON
ElasticSearch
GFT
GML
GMLAS
GPKG
GPSBabel
GPSTrackMaker
GPX
GeoJSON
GeoJSONSeq
GeoRSS
Geoconcept
Geomedia
HTF
HTTP
Idrisi
Interlis 1
Interlis 2
JML
JP2OpenJPEG
KML
LIBKML
MBTiles
MSSQLSpatial
MVT
MapInfo File
Memory
MySQL
NAS
NGW
ODBC
ODS
OGR_DODS
OGR_GMT
OGR_GRASS
OGR_OGDI
OGR_PDS
OGR_SDTS
OGR_VRT
OSM
OpenAir
OpenFileGDB
PCIDSK
PDF
PGDUMP
PGeo
PLSCENES
PostgreSQL
REC
S57
SEGUKOOA
SEGY
SOSI
SQLite
SUA
SVG
SXF
Selafin
TIGER
TopoJSON
UK .NTF
VDV
VFK
WAsP
WFS
WFS3
Walk
XLS
XLSX
XPlane
netCDF
```
* I tried to build `FIONA` from source, and manually add `GRASS` in the list of supported drivers

```
In [2]: !cat /usr/local/lib/python3.7/dist-packages/fiona/drvsupport.py | grep GRASS                                                                                            
    # GRASS 	GRASS 	No 	Yes 	No, needs libgrass
    ("GRASS", "r"),
```

* To build `Fiona` I used the following command from inside the src tree of a clone of the `Fiona GitHub master branch`:

```
sudo GDAL_CONFIG=/usr/bin/gdal-config pip3 install --no-binary fiona .
```

* I checked that `Fiona` was built agains the right version of `GDAL`:
```
In [3]: !fio --gdal-version                                                                                                                                                     
GDAL, version 2.4.0

In [4]: !gdal-config --version                                                                                                                                                  
2.4.0
```

* No luck .. the `GRASS` drivers are not available from `Fiona`:

In [5]: import fiona 
   ...: from fiona._drivers import GDALEnv 
   ...: env = GDALEnv()                                                                                                                                                         

In [6]:                                                                                                                                                                         

In [6]: env.start().drivers().keys()                                                                                                                                            
Out[6]: dict_keys(['OGR_GRASS', 'PCIDSK', 'netCDF', 'JP2OpenJPEG', 'PDF', 'MBTiles', 'EEDA', 'ESRI Shapefile', 'MapInfo File', 'UK .NTF', 'OGR_SDTS', 'S57', 'DGN', 'OGR_VRT', 'REC', 'Memory', 'BNA', 'CSV', 'NAS', 'GML', 'GPX', 'LIBKML', 'KML', 'GeoJSON', 'GeoJSONSeq', 'ESRIJSON', 'TopoJSON', 'Interlis 1', 'Interlis 2', 'OGR_GMT', 'GPKG', 'SQLite', 'OGR_DODS', 'ODBC', 'WAsP', 'PGeo', 'MSSQLSpatial', 'OGR_OGDI', 'PostgreSQL', 'MySQL', 'OpenFileGDB', 'XPlane', 'DXF', 'CAD', 'Geoconcept', 'GeoRSS', 'GPSTrackMaker', 'VFK', 'PGDUMP', 'OSM', 'GPSBabel', 'SUA', 'OpenAir', 'OGR_PDS', 'WFS', 'WFS3', 'SOSI', 'HTF', 'AeronavFAA', 'Geomedia', 'EDIGEO', 'GFT', 'SVG', 'CouchDB', 'Cloudant', 'Idrisi', 'ARCGEN', 'SEGUKOOA', 'SEGY', 'XLS', 'ODS', 'XLSX', 'ElasticSearch', 'Walk', 'Carto', 'AmigoCloud', 'SXF', 'Selafin', 'JML', 'PLSCENES', 'CSW', 'VDV', 'GMLAS', 'MVT', 'TIGER', 'AVCBin', 'AVCE00', 'NGW', 'HTTP'])

## Operating system
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

## Fiona and GDAL version and provenance

* Fiona version 1.8.6 built from source (GitHub master branch - commit # 417b94c21deb4745a39313891f51f67ebe98b871)
* GDAL 2.4.0 installed via `apt-get` from `Ubuntu GIS PPA`

**Comment by sgillies** [comment]
@epifanio GRASS format support isn't enabled by default, but you can turn it on after you import fiona by executing `fiona.supported_drivers["GRASS"] = "r"`.

**Comment by epifanio** [comment]
super cool! I didn't lknow It was possible to enable it without touching the src code.
The line that worked for me is:
```
import fiona
fiona.supported_drivers["OGR_GRASS"] = "r" 
```
then the line below works as expected!

```
import geopandas as gpd
gpd.read_file('GRASSDB/lLOCATION_NAME/MAPSET/vector/layername/head')
```

Thanks!

**Comment by jorisvandenbossche** [comment]
@sgillies Is there a reason it is not enabled by default? Not all aspects of such files supported in fiona's data model?

**Comment by sgillies** [comment]
@jorisvandenbossche incomplete driver implementations have been a support headache for GDAL/OGR (CAD formats especially) and I didn't want to enable all of the marginal and odd drivers in Fiona and invite the headache here. I kept GRASS out, mainly because I'm not very familiar with it and am unsure of how well it works. OGR can't write the GRASS format, so it's not very functional.

**Comment by lucadelu** [comment]
Hi, 
I'm trying to do the same, but I have some problem

```
>>> import fiona
>>> fiona.supported_drivers["OGR_GRASS"] = "r" 
>>> import geopandas as gpd
>>> gdf = gpd.read_file('/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/geopandas/io/file.py", line 294, in _read_file
    return _read_file_pyogrio(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/geopandas/io/file.py", line 547, in _read_file_pyogrio
    return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/pyogrio/geopandas.py", line 265, in read_dataframe
    result = read_func(
             ^^^^^^^^^^
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/pyogrio/raw.py", line 198, in read
    return ogr_read(
           ^^^^^^^^^
  File "pyogrio/_io.pyx", line 1240, in pyogrio._io.ogr_read
  File "pyogrio/_io.pyx", line 216, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: '/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head' not recognized as being in a supported file format. It might help to specify the correct driver explicitly by prefixing the file path with '<DRIVER>:', e.g. 'CSV:path'.
>>> gdf = gpd.read_file('OGR_GRASS:/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/geopandas/io/file.py", line 294, in _read_file
    return _read_file_pyogrio(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/geopandas/io/file.py", line 547, in _read_file_pyogrio
    return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/pyogrio/geopandas.py", line 265, in read_dataframe
    result = read_func(
             ^^^^^^^^^^
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/pyogrio/raw.py", line 198, in read
    return ogr_read(
           ^^^^^^^^^
  File "pyogrio/_io.pyx", line 1240, in pyogrio._io.ogr_read
  File "pyogrio/_io.pyx", line 220, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: OGR_GRASS:/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head: No such file or directory
```

however `ogrinfo` is working well

```
ogrinfo -al -so /home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head
Warning 1: GRASS warning: GISBASE environment variable was not set, using:
/home/lucadelu/github/grass/dist.x86_64-pc-linux-gnu
INFO: Open of `/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head'
      using driver `OGR_GRASS' successful.

Layer name: 0
Geometry: Line String
Feature Count: 1
Extent: (11.039880, 46.360327) - (11.041358, 46.361294)
Layer SRS WKT:
GEOGCRS["wgs84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS_1984",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 1,2

Layer name: 1
Geometry: Polygon
Feature Count: 1
Extent: (11.039880, 46.360327) - (11.041358, 46.361294)
Layer SRS WKT:
GEOGCRS["wgs84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS_1984",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 1,2
cat: Integer (0.0)
```

do you have any advice to solve the problem?

**Comment by sgillies** [comment]
@lucadelu in your traceback I see

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucadelu/gitlab/grass_agriculture_2025/venv/lib/python3.11/site-packages/geopandas/io/file.py", line 294, in _read_file
    return _read_file_pyogrio(
```

pyogrio is a different project from fiona. I can't help.

**Comment by lucadelu** [comment]
@sgillies thanks for the answer, I was able to read it changing the Geopandas io_engine with the following code

```
gpd.options.io_engine = "fiona"
```

and I'm now able to read my  vector.
I facing two problems.
First fiona read only the first layer (linestring) but I would like to get the second (polygon), is there a way to do this?

ogrinfo output

```
ogrinfo -al -so /home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head
Warning 1: GRASS warning: GISBASE environment variable was not set, using:
/home/lucadelu/github/grass/dist.x86_64-pc-linux-gnu
INFO: Open of `/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head'
      using driver `OGR_GRASS' successful.

Layer name: 0
Geometry: Line String
Feature Count: 1
Extent: (11.039880, 46.360327) - (11.041358, 46.361294)
Layer SRS WKT:
GEOGCRS["wgs84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS_1984",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 1,2

Layer name: 1
Geometry: Polygon
Feature Count: 1
Extent: (11.039880, 46.360327) - (11.041358, 46.361294)
Layer SRS WKT:
GEOGCRS["wgs84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS_1984",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 1,2
cat: Integer (0.0)
```

geopandas with fiona output

```
gdf = gpd.read_file('/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head')
gdf
                                            geometry
0  LINESTRING (11.0399 46.36094, 11.03989 46.3609...
```

second is that my GeoDataFrame has only the geometry and not the attributes (maybe this is not related to fiona)

**Comment by lucadelu** [comment]
@sgillies I found the way sorry

```
fiona.listlayers('/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head')
gdf = gpd.read_file('/home/lucadelu/grassdata/world_latlong_wgs84/lucadelu/vector/field_buffer/head', layer='1')
```
