### ISSUE TITLE
Fiona (and Geopandas) error when opening empty Sentinel-2 cloud mask

### ISSUE THREAD

**Issue by Melykuti** [Toblerity/Fiona#809]
I am processing the cloud masks (a set of polygons which represent the location of clouds) of Sentinel-2 optical satellite images. I would like to read them using Geopandas. This works usually. I noticed that when I open an empty cloud mask (when there is no cloud over the area), then Geopandas crashes. If I do it in pure Fiona (installed with pip3), then it crashes too. It behaves reproducibly so.

I have tried it
* under Fedora 28 with Fiona 1.8.0 and OsGeo 2.3.2, and
* under Debian 10.1 with Fiona 1.8.8 and 1.8.9.post2 and GDAL 2.4.0 (libgdal-dev=2.4.0+dfsg-1+b1 and python3-gdal=2.4.0+dfsg-1+b1).

The expected behaviour is that it does not crash. Ideally, I guess, I would like Geopandas to return a table of zero length.

#### Steps to reproduce:
(By using the attached data files [MSK_CLOUDS_B00.zip](https://github.com/Toblerity/Fiona/files/3761180/MSK_CLOUDS_B00.zip).)

    >>> import fiona
    >>> e=fiona.open('MSK_CLOUDS_B00_empty.gml')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.7/dist-packages/fiona/env.py", line 406, in wrapper
        return f(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/fiona/__init__.py", line 253, in open
        layer=layer, enabled_drivers=enabled_drivers, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/fiona/collection.py", line 159, in __init__
        self.session.start(self, **kwargs)
      File "fiona/ogrext.pyx", line 497, in fiona.ogrext.Session.start
    ValueError: Null layer: ''

    >>> import geopandas
    >>> ge=geopandas.read_file('MSK_CLOUDS_B00_empty.gml')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.7/dist-packages/geopandas/io/file.py", line 71, in read_file
        with reader(path_or_bytes, **kwargs) as features:
      File "/usr/local/lib/python3.7/dist-packages/fiona/env.py", line 397, in wrapper
        return f(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/fiona/__init__.py", line 253, in open
        layer=layer, enabled_drivers=enabled_drivers, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/fiona/collection.py", line 159, in __init__
        self.session.start(self, **kwargs)
      File "fiona/ogrext.pyx", line 497, in fiona.ogrext.Session.start
    ValueError: Null layer: ''

Related issues: #789 and perhaps https://github.com/geopandas/geopandas/issues/649

**Comment by sgillies** [comment]
@Melykuti I looked in the GML files and am seeing XML like

```
<?xml version="1.0" encoding="UTF-8"?>
<eop:Mask xmlns:eop="http://www.opengis.net/eop/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="S2A_OPER_MSK_CLOUDS_SGS__20180828T121318_A016621_T34TCS_B00_MSIL1C">
  <gml:name>MSK_CLOUDS pixels mask from data-strip S2A_OPER_MSK_CLOUDS_SGS__20180828T121318_A016621_T34TCS_B00_MSIL1C</gml:name>
  <eop:maskMembers/>
</eop:Mask>
```

This is not something that Fiona (and OGR, which is what Fiona uses to read GML) can understand.

See https://gdal.org/drivers/vector/gml.html for details and caveats about OGR's GML format driver.

**Comment by sgillies** [comment]
Closing in favor of #810.
