### ISSUE TITLE
enum34 dependency breaking installation into env with Python 3.7.5

### ISSUE THREAD

**Issue by jseery** [Toblerity/Fiona#841]
Hi there,

I'm attempting to re-install a project that has fiona as an implicit dependency (a package depends on geopandas which depends on fiona). I'm using Python 3.7.5 but fiona is still trying to install enum34, which is only supposed to be for <3.4. Unfortunately, the enum34 dependency is preventing me from installing the rest of the project.

I see this PR, which I think would fix the issue, was merged already: https://github.com/Toblerity/Fiona/pull/770, 
but that this later version hasn't been released to PyPI yet.
Do you folks have an existing plan/timeline to release following this linked PR, with the enum34 dependency removed?

## Expected behavior and actual behavior.

Expected installation to finish, but is interrupted after fiona installs enum34 and packages installing afterwards break.

## Steps to reproduce the problem.

I was able to reproduce with this minimal pyproject.toml, installed via poetry 0.12.17 (https://github.com/sdispater/poetry)
```
[tool.poetry]
name = "env_test"
version = "0.1.0"
description = ""
authors = ["Name, <email@email.com>"]

[tool.poetry.dependencies]
python = "^3.7.5"
fiona = "*"
pendulum = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Resulting output when I attempt to install is pasted below. Fiona installs just fine but downstream packages break - it seems related to this issue:
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag
```
poetry install
Creating virtualenv env-test-py3.7 in /Users/jseery/projects/bitbucket/env_test/.venv
Installing dependencies from lock file


Package operations: 18 installs, 0 updates, 0 removals

  - Installing more-itertools (8.0.0)
  - Installing zipp (0.6.0)
  - Installing click (7.0)
  - Installing importlib-metadata (1.1.0)
  - Installing six (1.13.0)
  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.3.0)
  - Installing click-plugins (1.1.1)
  - Installing cligj (0.5.0)
  - Installing enum34 (1.1.6)
  - Installing munch (2.5.0)
  - Installing pluggy (0.13.1)
  - Installing py (1.8.0)
  - Installing python-dateutil (2.8.1)
  - Installing pytzdata (2019.3)
  - Installing fiona (1.8.11)
  - Installing pendulum (2.0.5)

[EnvCommandError]
Command ['/Users/jseery/projects/bitbucket/env_test/.venv/bin/python', '-m', 'pip', 'install', '--no-deps', 'pendulum==2.0.5'] errored with the following return code 1, and output:
Collecting pendulum==2.0.5
  Using cached https://files.pythonhosted.org/packages/e0/f9/ea90c2c8f0d9b6a733f6231fac6d07476b68271bcf02bab0053888ea0fb3/pendulum-2.0.5.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Users/jseery/projects/bitbucket/env_test/.venv/bin/python /Users/jseery/projects/bitbucket/env_test/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /
private/var/folders/1v/k4htfv5n4vj7w1d87_xj3fqm7f8k39/T/pip-build-env-bihujgpu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12'
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/Users/jseery/.pyenv/versions/3.7.5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/jseery/.pyenv/versions/3.7.5/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/jseery/projects/bitbucket/env_test/.venv/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/Users/jseery/projects/bitbucket/env_test/.venv/lib/python3.7/site-packages/pip/_internal/__init__.py", line 4, in <module>
      import locale
    File "/Users/jseery/.pyenv/versions/3.7.5/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/Users/jseery/.pyenv/versions/3.7.5/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/jseery/projects/bitbucket/env_test/.venv/bin/python /Users/jseery/projects/bitbucket/env_test/.venv/lib/python3.7/site-packages/pip install --ig
nore-installed --no-user --prefix /private/var/folders/1v/k4htfv5n4vj7w1d87_xj3fqm7f8k39/T/pip-build-env-bihujgpu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https:/
/pypi.org/simple -- 'poetry>=0.12' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

## Operating system

Mac OS X 10.13.6

## Fiona and GDAL version and provenance

latest Fiona version available on PyPI (1.8.11)

**Comment by sgillies** [comment]
@jseery I think this may be a problem specific to poetry. I can't reproduce it using pip alone.

Below I've created a new Python environment and I run `pip list` before and after `pip install fiona`. There is no enum34 in my environment.

```
$ mkvirtualenv testfiona -p /usr/local/bin/python3.6
Running virtualenv with interpreter /usr/local/bin/python3.6
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/seang/envs/testfiona/bin/python3.6
Also creating executable in /Users/seang/envs/testfiona/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/seang/envs/testfiona/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/seang/envs/testfiona/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/seang/envs/testfiona/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/seang/envs/testfiona/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/seang/envs/testfiona/bin/get_env_details
(testfiona) vas-y:~ seang$ pip list
Package    Version
---------- -------
pip        19.3.1
setuptools 42.0.2
wheel      0.33.6
(testfiona) vas-y:~ seang$ pip install fiona
Collecting fiona
  Downloading https://files.pythonhosted.org/packages/2d/0f/72e2999c1ded88036172ffcfe6032e013d81e87fec300d96d59e64d0bc47/Fiona-1.8.11-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (17.9MB)
     |████████████████████████████████| 17.9MB 785kB/s
Collecting six>=1.7
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting click<8,>=4.0
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting click-plugins>=1.0
  Using cached https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl
Collecting attrs>=17
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting munch
  Using cached https://files.pythonhosted.org/packages/cc/ab/85d8da5c9a45e072301beb37ad7f833cd344e04c817d97e0cc75681d248f/munch-2.5.0-py2.py3-none-any.whl
Collecting cligj>=0.5
  Using cached https://files.pythonhosted.org/packages/e4/be/30a58b4b0733850280d01f8bd132591b4668ed5c7046761098d665ac2174/cligj-0.5.0-py3-none-any.whl
Installing collected packages: six, click, click-plugins, attrs, munch, cligj, fiona
Successfully installed attrs-19.3.0 click-7.0 click-plugins-1.1.1 cligj-0.5.0 fiona-1.8.11 munch-2.5.0 six-1.13.0
(testfiona) vas-y:~ seang$ pip list
Package       Version
------------- -------
attrs         19.3.0
Click         7.0
click-plugins 1.1.1
cligj         0.5.0
Fiona         1.8.11
munch         2.5.0
pip           19.3.1
setuptools    42.0.2
six           1.13.0
wheel         0.33.6
```

**Comment by sgillies** [comment]
Yeah, this has to be a poetry bug. But yes, I should cherry pick the work in #815 and make a fiona 1.8.12. I'll create a new issue for that.

**Comment by jseery** [comment]
thank you @sgillies! Incredibly helpful. fiona 1.8.12  resolved the issue for me,
but I'll try to replicate what you just did with pip and open an issue with poetry.
