### ISSUE TITLE
Error loading zip+s3 on ubuntu 18.04 

### ISSUE THREAD

**Issue by milosimr** [Toblerity/Fiona#846]
Trying to open file on S3 using fiona:
```python
key = '/DataImport/BLOCK_I1_Compilation_1_Feature.gdb.zip'
file_url = 'zip+s3://' + 'bucket' + key
with fiona.open(file_url) as src:
    print(len(src))
```

fails on Ubuntu 18.04, with fiona-1.8.13 installed using `pip3 install fiona` with the following error:

```
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 74, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 270, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: '/vsizip/vsis3/bucket/DataImport/BLOCK_I1_Compilation_1_Feature.gdb.zip' does not exist in the file system, and is not recognized as a supported dataset name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "read_fiona.py", line 23, in <module>
    get_layers()
  File "read_fiona.py", line 17, in get_layers
    with fiona.open(file_url) as src:
  File "/home/ahab/.local/lib/python3.6/site-packages/fiona/env.py", line 407, in wrapper
    return f(*args, **kwargs)
  File "/home/ahab/.local/lib/python3.6/site-packages/fiona/__init__.py", line 254, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/home/ahab/.local/lib/python3.6/site-packages/fiona/collection.py", line 154, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 484, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 81, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: '/vsizip/vsis3/bucket/DataImport/BLOCK_I1_Compilation_1_Feature.gdb.zip' does not exist in the file system, and is not recognized as a supported dataset name.
```

It works as inteded on MacOS Catalina.

**Comment by sgillies** [comment]
@milosimr on Ubuntu you must set an environment variable to point to the SSL certs. See https://github.com/mapbox/rasterio#ssl-certs. I apologize for Fiona's docs being behind the times.
