### ISSUE TITLE
Coveralls does not include results of all CI's

### ISSUE THREAD

**Issue by rbuffat** [Toblerity/Fiona#877]
It looks that coveralls includes only results of one CI provider.  

In https://github.com/Toblerity/Fiona/pull/875/commits/b890f5c2007e783f45984107e34c88f65a0fd15b only the results of travis are included.

I'm not sure if coveralls supports multiple CI's at all. 

Codecov claims that it merges reports from multiple CI providers: https://docs.codecov.io/docs/frequently-asked-questions#section-does-codecov-merge-reports-for-multiple-containers-and-or-ci-providers

**Comment by rbuffat** [comment]
After testing out how codecov works, I noticed that coveralls is not setup on appveyor. I'm not sure why. 

Adding coveralls to appveyor requires setting a token:
```
Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\coveralls\cli.py", line 61, in main
    service_name=options['--service'])
  File "C:\Python36-x64\Lib\site-packages\coveralls\api.py", line 64, in __init__
    self.ensure_token()
  File "C:\Python36-x64\Lib\site-packages\coveralls\api.py", line 73, in ensure_token
    self.config_filename))
coveralls.exception.CoverallsException: Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var. 
```

Codecov does not require a token for travis and appveyor. https://codecov.io/gh/rbuffat/Fiona/branch/try_codecov

**Comment by rbuffat** [comment]
Closed with https://github.com/Toblerity/Fiona/pull/885
