### ISSUE TITLE
fio cat failing with --dst-crs 

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#952]
In https://github.com/mapbox/rasterio/issues/1961 `fio cat --dst-crs EPSG:3857` is reported to fail and I can reproduce it with fiona's testing data and a version installed from a wheel.

```
$ fio cat ~/projects/Fiona/tests/data/coutwildrnp.shp --dst-crs EPSG:3857
ERROR:fiona.fio.cat:Exception caught during processing
Traceback (most recent call last):
  File "/home/sean/.local/pipx/venvs/fiona/lib/python3.7/site-packages/fiona/fio/cat.py", line 82, in cat
    feat['bbox'] = fiona.bounds(g)
  File "/home/sean/.local/pipx/venvs/fiona/lib/python3.7/site-packages/fiona/__init__.py", line 406, in bounds
    return _bounds(geom)
  File "fiona/ogrext.pyx", line 115, in fiona.ogrext._bounds
IndexError: tuple index out of range
Aborted!
```

If I comment out https://github.com/Toblerity/Fiona/blob/maint-1.8/fiona/fio/cat.py#L79, the command succeeds. We have a problem with antimeridian cutting and GDAL 2.4.4 such that the transformed geometries are empty multipolygons. We shouldn't be using antimerdian cutting for any projected coordinate system. We'll need a fix and a new release ASAP.

**Comment by sgillies** [comment]
Fixed in 1.8.17.
